export const defaultPartyData = [
  { id: 'party-1', name: 'Thorin Ironforge', class: 'Fighter', level: 5, ac: 18, maxHp: 52, currentHp: 52, initiative: 0, speed: 30, notes: 'Battlemaster. Shield Bearer.', resources: [{ name: 'Second Wind', current: 1, max: 1 }, { name: 'Action Surge', current: 1, max: 1 }, { name: 'Superiority Dice', current: 4, max: 4 }], str: 18, dex: 14, con: 16, int: 10, wis: 12, cha: 8, spellStat: null },
  { id: 'party-2', name: 'Elara Moonwhisper', class: 'Wizard', level: 5, ac: 13, maxHp: 28, currentHp: 28, initiative: 0, speed: 30, notes: 'Evocation specialist. Low HP!', resources: [{ name: '1st Level Slots', current: 4, max: 4 }, { name: '2nd Level Slots', current: 3, max: 3 }, { name: '3rd Level Slots', current: 2, max: 2 }], str: 8, dex: 14, con: 12, int: 18, wis: 13, cha: 10, spellStat: 'int' },
  { id: 'party-3', name: 'Bramble Thornfoot', class: 'Rogue', level: 5, ac: 15, maxHp: 38, currentHp: 38, initiative: 0, speed: 35, notes: 'Arcane Trickster. Sneak attack 3d6.', resources: [{ name: '1st Level Slots', current: 3, max: 3 }], str: 10, dex: 18, con: 14, int: 14, wis: 12, cha: 10, spellStat: 'int' },
];

export const defaultEnemyTemplates = [
  { id: 'tpl-1', name: 'Goblin', ac: 15, maxHp: 7, speed: 30, cr: '1/4', notes: 'Nimble Escape. Pack tactics.', isNpc: false, str: 8, dex: 14, con: 10, int: 10, wis: 8, cha: 8, actions: [{ name: 'Scimitar', description: '+4 to hit, 5 ft., 1d6+2 slashing' }, { name: 'Shortbow', description: '+4 to hit, range 80/320 ft., 1d6+2 piercing' }] },
  { id: 'tpl-2', name: 'Orc', ac: 13, maxHp: 15, speed: 30, cr: '1/2', notes: 'Aggressive: Bonus action to move toward enemy.', isNpc: false, str: 16, dex: 12, con: 16, int: 7, wis: 11, cha: 10, actions: [{ name: 'Greataxe', description: '+5 to hit, 5 ft., 1d12+3 slashing' }, { name: 'Javelin', description: '+5 to hit, range 30/120 ft., 1d6+3 piercing' }] },
  { id: 'tpl-3', name: 'Skeleton', ac: 13, maxHp: 13, speed: 30, cr: '1/4', notes: 'Vulnerable to bludgeoning. Immune to poison.', isNpc: false, str: 10, dex: 14, con: 15, int: 6, wis: 8, cha: 5, actions: [{ name: 'Shortsword', description: '+4 to hit, 5 ft., 1d6+2 piercing' }, { name: 'Shortbow', description: '+4 to hit, range 80/320 ft., 1d6+2 piercing' }] },
  { id: 'tpl-4', name: 'Zombie', ac: 8, maxHp: 22, speed: 20, cr: '1/4', notes: 'Undead Fortitude: CON save (5+dmg) to stay at 1 HP.', isNpc: false, str: 13, dex: 6, con: 16, int: 3, wis: 6, cha: 5, actions: [{ name: 'Slam', description: '+3 to hit, 5 ft., 1d6+1 bludgeoning' }] },
  { id: 'tpl-5', name: 'Wolf', ac: 13, maxHp: 11, speed: 40, cr: '1/4', notes: 'Pack Tactics. Keen Hearing/Smell (adv on Perception).', isNpc: false, str: 12, dex: 15, con: 12, int: 3, wis: 12, cha: 6, actions: [{ name: 'Bite', description: '+4 to hit, 5 ft., 2d4+2 piercing. DC 11 STR or prone.' }] },
  { id: 'tpl-6', name: 'Bandit', ac: 12, maxHp: 11, speed: 30, cr: '1/8', notes: '', isNpc: false, str: 11, dex: 12, con: 12, int: 10, wis: 10, cha: 10, actions: [{ name: 'Scimitar', description: '+3 to hit, 5 ft., 1d6+1 slashing' }, { name: 'Light Crossbow', description: '+3 to hit, range 80/320 ft., 1d8+1 piercing' }] },
  { id: 'tpl-7', name: 'Ogre', ac: 11, maxHp: 59, speed: 40, cr: '2', notes: 'Large. Darkvision 60ft.', isNpc: false, str: 19, dex: 8, con: 16, int: 5, wis: 7, cha: 7, actions: [{ name: 'Greatclub', description: '+6 to hit, 5 ft., 2d8+4 bludgeoning' }, { name: 'Javelin', description: '+6 to hit, range 30/120 ft., 2d6+4 piercing' }] },
  { id: 'tpl-8', name: 'Town Guard', ac: 16, maxHp: 11, speed: 30, cr: '1/8', notes: 'Chain shirt, shield.', isNpc: true, str: 13, dex: 12, con: 12, int: 10, wis: 11, cha: 10, actions: [{ name: 'Spear', description: '+3 to hit, 5 ft. or range 20/60 ft., 1d6+1 piercing' }] },
  { id: 'tpl-9', name: 'Commoner', ac: 10, maxHp: 4, speed: 30, cr: '0', notes: '', isNpc: true, str: 10, dex: 10, con: 10, int: 10, wis: 10, cha: 10, actions: [{ name: 'Club', description: '+2 to hit, 5 ft., 1d4 bludgeoning' }] },
];
