// Spell data in 2024 PHB format
// Each spell includes: name, level, school, classes, castingTime, range, components, duration, description, higherLevels, concentration, ritual

export const spells = [
  // Cantrips
  {
    name: "Acid Splash",
    level: 0,
    school: "Evocation",
    classes: ["Sorcerer", "Wizard"],
    castingTime: "Action",
    range: "60 feet",
    components: "V, S",
    duration: "Instantaneous",
    description: "You create an acidic bubble at a point within range, where it explodes in a 5-foot-radius Sphere. Each creature in that Sphere must succeed on a Dexterity saving throw or take 1d6 Acid damage.",
    higherLevels: "The damage increases by 1d6 when you reach levels 5 (2d6), 11 (3d6), and 17 (4d6).",
    concentration: false,
    ritual: false
  },
  {
    name: "Blade Ward",
    level: 0,
    school: "Abjuration",
    classes: ["Bard", "Sorcerer", "Warlock", "Wizard"],
    castingTime: "Action",
    range: "Self",
    components: "V, S",
    duration: "Concentration, up to 1 minute",
    description: "Whenever a creature makes an attack roll against you before the spell ends, the attacker subtracts 1d4 from the attack roll.",
    higherLevels: null,
    concentration: true,
    ritual: false
  },
  {
    name: "Chill Touch",
    level: 0,
    school: "Necromancy",
    classes: ["Sorcerer", "Warlock", "Wizard"],
    castingTime: "Action",
    range: "Touch",
    components: "V, S",
    duration: "Instantaneous",
    description: "You touch one creature, and Necrotic energy washes over it. The target must succeed on a Constitution saving throw or take 1d10 Necrotic damage. Until the start of your next turn, the target can't regain Hit Points.",
    higherLevels: "The damage increases by 1d10 when you reach levels 5 (2d10), 11 (3d10), and 17 (4d10).",
    concentration: false,
    ritual: false
  },
  {
    name: "Dancing Lights",
    level: 0,
    school: "Illusion",
    classes: ["Bard", "Sorcerer", "Wizard"],
    castingTime: "Action",
    range: "120 feet",
    components: "V, S, M (a bit of phosphorus)",
    duration: "Concentration, up to 1 minute",
    description: "You create up to four torch-size lights within range, making them appear as torches, lanterns, or glowing orbs that hover for the duration. You can combine the four lights into one glowing, vaguely humanoid form of Medium size. Whichever form you choose, each light sheds Dim Light in a 10-foot radius.\n\nAs a Bonus Action, you can move the lights up to 60 feet to a new spot within range. A light must be within 20 feet of another light created by this spell, and a light winks out if it exceeds the spell's range.",
    higherLevels: null,
    concentration: true,
    ritual: false
  },
  {
    name: "Druidcraft",
    level: 0,
    school: "Transmutation",
    classes: ["Druid"],
    castingTime: "Action",
    range: "30 feet",
    components: "V, S",
    duration: "Instantaneous",
    description: "Whispering to the spirits of nature, you create one of the following effects within range:\n\nWeather Sensor. You create a Tiny, harmless sensory effect that predicts what the weather will be at your location for the next 24 hours. The effect might manifest as a golden orb for clear skies, a cloud for rain, falling snowflakes for snow, and so on. This effect persists for 1 round.\n\nBloom. You instantly make a flower blossom, a seed pod open, or a leaf bud bloom.\n\nSensory Effect. You create a harmless sensory effect, such as falling leaves, a puff of wind, the sound of a small animal, or the faint odor of skunk. The effect must fit in a 5-foot Cube.\n\nFire Play. You instantly light or snuff out a candle, a torch, or a small campfire.",
    higherLevels: null,
    concentration: false,
    ritual: false
  },
  {
    name: "Eldritch Blast",
    level: 0,
    school: "Evocation",
    classes: ["Warlock"],
    castingTime: "Action",
    range: "120 feet",
    components: "V, S",
    duration: "Instantaneous",
    description: "You hurl a beam of crackling energy. Make a ranged spell attack against one creature or object in range. On a hit, the target takes 1d10 Force damage.",
    higherLevels: "The spell creates more than one beam when you reach higher levels: two beams at level 5, three beams at level 11, and four beams at level 17. You can direct the beams at the same target or at different ones. Make a separate attack roll for each beam.",
    concentration: false,
    ritual: false
  },
  {
    name: "Fire Bolt",
    level: 0,
    school: "Evocation",
    classes: ["Sorcerer", "Wizard"],
    castingTime: "Action",
    range: "120 feet",
    components: "V, S",
    duration: "Instantaneous",
    description: "You hurl a mote of fire at a creature or object within range. Make a ranged spell attack against the target. On a hit, the target takes 1d10 Fire damage. A flammable object hit by this spell catches fire if it isn't being worn or carried.",
    higherLevels: "The damage increases by 1d10 when you reach levels 5 (2d10), 11 (3d10), and 17 (4d10).",
    concentration: false,
    ritual: false
  },
  {
    name: "Guidance",
    level: 0,
    school: "Divination",
    classes: ["Cleric", "Druid"],
    castingTime: "Action",
    range: "Touch",
    components: "V, S",
    duration: "Concentration, up to 1 minute",
    description: "You touch a willing creature and choose a skill. Until the spell ends, the creature adds 1d4 to any ability check using the chosen skill.",
    higherLevels: null,
    concentration: true,
    ritual: false
  },
  {
    name: "Light",
    level: 0,
    school: "Evocation",
    classes: ["Bard", "Cleric", "Sorcerer", "Wizard"],
    castingTime: "Action",
    range: "Touch",
    components: "V, M (a firefly or phosphorescent moss)",
    duration: "1 hour",
    description: "You touch one object that is no larger than 10 feet in any dimension. Until the spell ends, the object sheds Bright Light in a 20-foot radius and Dim Light for an additional 20 feet. The light can be colored as you like.\n\nCompletely covering the object with something opaque blocks the light. The spell ends if you cast it again.",
    higherLevels: null,
    concentration: false,
    ritual: false
  },
  {
    name: "Mage Hand",
    level: 0,
    school: "Conjuration",
    classes: ["Bard", "Sorcerer", "Warlock", "Wizard"],
    castingTime: "Action",
    range: "30 feet",
    components: "V, S",
    duration: "1 minute",
    description: "A spectral, floating hand appears at a point you choose within range. The hand lasts for the duration. The hand vanishes if it is ever more than 30 feet away from you or if you cast this spell again.\n\nYou can use the hand to manipulate an object, open an unlocked door or container, stow or retrieve an item from an open container, or pour the contents out of a vial.\n\nYou can move the hand up to 30 feet each time you use it. The hand can't attack, activate magic items, or carry more than 10 pounds.",
    higherLevels: null,
    concentration: false,
    ritual: false
  },
  {
    name: "Mending",
    level: 0,
    school: "Transmutation",
    classes: ["Bard", "Cleric", "Druid", "Sorcerer", "Wizard"],
    castingTime: "1 minute",
    range: "Touch",
    components: "V, S, M (two lodestones)",
    duration: "Instantaneous",
    description: "This spell repairs a single break or tear in an object you touch, such as a broken chain link, two halves of a broken key, a torn cloak, or a leaking wineskin. As long as the break or tear is no larger than 1 foot in any dimension, you mend it, leaving no trace of the former damage.\n\nThis spell can physically repair a magic item, but it can't restore magic to such an object.",
    higherLevels: null,
    concentration: false,
    ritual: false
  },
  {
    name: "Message",
    level: 0,
    school: "Transmutation",
    classes: ["Bard", "Sorcerer", "Wizard"],
    castingTime: "Action",
    range: "120 feet",
    components: "S, M (a copper wire)",
    duration: "1 round",
    description: "You point toward a creature within range and whisper a message. The target (and only the target) hears the message and can reply in a whisper that only you can hear.\n\nYou can cast this spell through solid objects if you are familiar with the target and know it is beyond the barrier. Magical silence, 1 foot of stone, 1 inch of common metal, a thin sheet of lead, or 3 feet of wood blocks the spell.",
    higherLevels: null,
    concentration: false,
    ritual: false
  },
  {
    name: "Minor Illusion",
    level: 0,
    school: "Illusion",
    classes: ["Bard", "Sorcerer", "Warlock", "Wizard"],
    castingTime: "Action",
    range: "30 feet",
    components: "S, M (a bit of fleece)",
    duration: "1 minute",
    description: "You create a sound or an image of an object within range that lasts for the duration. See the descriptions below for the effects of each. The illusion ends if you dismiss it as a Bonus Action or cast this spell again.\n\nSound. If you create a sound, its volume can range from a whisper to a scream. It can be your voice, someone else's voice, a lion's roar, a beating of drums, or any other sound you choose. The sound continues unabated throughout the duration, or you can make discrete sounds at different times before the spell ends.\n\nImage. If you create an image of an object—such as a chair, muddy footprints, or a small chest—it must be no larger than a 5-foot Cube. The image can't create sound, light, smell, or any other sensory effect. Physical interaction with the image reveals it to be an illusion, since things can pass through it.",
    higherLevels: null,
    concentration: false,
    ritual: false
  },
  {
    name: "Poison Spray",
    level: 0,
    school: "Necromancy",
    classes: ["Druid", "Sorcerer", "Warlock", "Wizard"],
    castingTime: "Action",
    range: "30 feet",
    components: "V, S",
    duration: "Instantaneous",
    description: "You spray toxic mist at a creature within range. Make a ranged spell attack against the target. On a hit, the target takes 1d12 Poison damage.",
    higherLevels: "The damage increases by 1d12 when you reach levels 5 (2d12), 11 (3d12), and 17 (4d12).",
    concentration: false,
    ritual: false
  },
  {
    name: "Prestidigitation",
    level: 0,
    school: "Transmutation",
    classes: ["Bard", "Sorcerer", "Warlock", "Wizard"],
    castingTime: "Action",
    range: "10 feet",
    components: "V, S",
    duration: "Up to 1 hour",
    description: "This spell is a minor magical trick that novice spellcasters use for practice. You create one of the following magical effects within range:\n\nSensory Effect. You create an instantaneous, harmless sensory effect, such as a shower of sparks, a puff of wind, faint musical notes, or an odd odor.\n\nFire Play. You instantaneously light or snuff out a candle, a torch, or a small campfire.\n\nClean or Soil. You instantaneously clean or soil an object no larger than 1 cubic foot.\n\nMinor Sensation. You chill, warm, or flavor up to 1 cubic foot of nonliving material for 1 hour.\n\nMagic Mark. You make a color, a small mark, or a symbol appear on an object or a surface for 1 hour.\n\nMinor Creation. You create a nonmagical trinket or an illusory image that can fit in your hand. It lasts until the end of your next turn. A trinket can deal no damage and has no monetary worth.\n\nYou can have up to three of this spell's non-instantaneous effects active at a time, and you can dismiss such an effect as a Bonus Action.",
    higherLevels: null,
    concentration: false,
    ritual: false
  },
  {
    name: "Produce Flame",
    level: 0,
    school: "Conjuration",
    classes: ["Druid"],
    castingTime: "Bonus Action",
    range: "Self",
    components: "V, S",
    duration: "10 minutes",
    description: "A flickering flame appears in your hand and remains there for the duration. While there, the flame emits no heat and ignites nothing, and it sheds Bright Light in a 20-foot radius and Dim Light for an additional 20 feet. The spell ends if you cast it again.\n\nUntil the spell ends, you can take a Magic action to hurl fire at a creature or an object within 60 feet of you. Make a ranged spell attack. On a hit, the target takes 1d8 Fire damage.",
    higherLevels: "The damage increases by 1d8 when you reach levels 5 (2d8), 11 (3d8), and 17 (4d8).",
    concentration: false,
    ritual: false
  },
  {
    name: "Ray of Frost",
    level: 0,
    school: "Evocation",
    classes: ["Sorcerer", "Wizard"],
    castingTime: "Action",
    range: "60 feet",
    components: "V, S",
    duration: "Instantaneous",
    description: "A frigid beam of blue-white light streaks toward a creature within range. Make a ranged spell attack against the target. On a hit, it takes 1d8 Cold damage, and its Speed is reduced by 10 feet until the start of your next turn.",
    higherLevels: "The damage increases by 1d8 when you reach levels 5 (2d8), 11 (3d8), and 17 (4d8).",
    concentration: false,
    ritual: false
  },
  {
    name: "Resistance",
    level: 0,
    school: "Abjuration",
    classes: ["Cleric", "Druid"],
    castingTime: "Action",
    range: "Touch",
    components: "V, S",
    duration: "Concentration, up to 1 minute",
    description: "You touch one willing creature. Before the spell ends, the target can add 1d4 to one saving throw of its choice. It can roll the die before or after making the saving throw. The spell then ends.",
    higherLevels: null,
    concentration: true,
    ritual: false
  },
  {
    name: "Sacred Flame",
    level: 0,
    school: "Evocation",
    classes: ["Cleric"],
    castingTime: "Action",
    range: "60 feet",
    components: "V, S",
    duration: "Instantaneous",
    description: "Flame-like radiance descends on a creature that you can see within range. The target must succeed on a Dexterity saving throw or take 1d8 Radiant damage. The target gains no benefit from Half Cover or Three-Quarters Cover for this save.",
    higherLevels: "The damage increases by 1d8 when you reach levels 5 (2d8), 11 (3d8), and 17 (4d8).",
    concentration: false,
    ritual: false
  },
  {
    name: "Shocking Grasp",
    level: 0,
    school: "Evocation",
    classes: ["Sorcerer", "Wizard"],
    castingTime: "Action",
    range: "Touch",
    components: "V, S",
    duration: "Instantaneous",
    description: "Lightning springs from you to a creature that you try to touch. Make a melee spell attack against the target. On a hit, the target takes 1d8 Lightning damage, and it can't take Reactions until the start of its next turn.",
    higherLevels: "The damage increases by 1d8 when you reach levels 5 (2d8), 11 (3d8), and 17 (4d8).",
    concentration: false,
    ritual: false
  },
  {
    name: "Spare the Dying",
    level: 0,
    school: "Necromancy",
    classes: ["Cleric"],
    castingTime: "Action",
    range: "15 feet",
    components: "V, S",
    duration: "Instantaneous",
    description: "Choose a creature within range that has 0 Hit Points and isn't dead. The creature becomes Stable.",
    higherLevels: null,
    concentration: false,
    ritual: false
  },
  {
    name: "Thaumaturgy",
    level: 0,
    school: "Transmutation",
    classes: ["Cleric"],
    castingTime: "Action",
    range: "30 feet",
    components: "V",
    duration: "Up to 1 minute",
    description: "You manifest a minor wonder, a sign of supernatural power, within range. You create one of the following magical effects within range:\n\nBooming Voice. Your voice booms up to three times as loud as normal for 1 minute.\n\nFlame Flicker. You cause flames to flicker, brighten, dim, or change color for 1 minute.\n\nHarmless Tremor. You cause harmless tremors in the ground for 1 minute.\n\nSound Effect. You create an instantaneous sound that originates from a point of your choice within range, such as a rumble of thunder, the cry of a raven, or ominous whispers.\n\nWindow or Door Control. You instantaneously cause an unlocked door or window to fly open or slam shut.\n\nAltered Eyes. You alter the appearance of your eyes for 1 minute.\n\nIf you cast this spell multiple times, you can have up to three of its 1-minute effects active at a time, and you can dismiss such an effect as a Bonus Action.",
    higherLevels: null,
    concentration: false,
    ritual: false
  },
  {
    name: "Toll the Dead",
    level: 0,
    school: "Necromancy",
    classes: ["Cleric", "Warlock", "Wizard"],
    castingTime: "Action",
    range: "60 feet",
    components: "V, S",
    duration: "Instantaneous",
    description: "You point at one creature you can see within range, and the sound of a dolorous bell fills the air around it for a moment. The target must succeed on a Wisdom saving throw or take 1d8 Necrotic damage. If the target is missing any of its Hit Points, it instead takes 1d12 Necrotic damage.",
    higherLevels: "The damage increases by one die when you reach levels 5 (2d8 or 2d12), 11 (3d8 or 3d12), and 17 (4d8 or 4d12).",
    concentration: false,
    ritual: false
  },
  {
    name: "True Strike",
    level: 0,
    school: "Divination",
    classes: ["Bard", "Sorcerer", "Warlock", "Wizard"],
    castingTime: "Action",
    range: "Self",
    components: "S, M (a weapon with which you have proficiency and that is worth 1+ CP)",
    duration: "Instantaneous",
    description: "Guided by a flash of magical insight, you make one attack with the weapon used in the spell's casting. The attack uses your spellcasting ability for the attack and damage rolls instead of using Strength or Dexterity. If the attack deals damage, it can be Radiant damage or the weapon's normal damage type (your choice).",
    higherLevels: "The attack deals extra Radiant damage when you reach levels 5 (1d6), 11 (2d6), and 17 (3d6).",
    concentration: false,
    ritual: false
  },
  {
    name: "Vicious Mockery",
    level: 0,
    school: "Enchantment",
    classes: ["Bard"],
    castingTime: "Action",
    range: "60 feet",
    components: "V",
    duration: "Instantaneous",
    description: "You unleash a string of insults laced with subtle enchantments at one creature you can see and that can hear you within range. The target must succeed on a Wisdom saving throw or take 1d6 Psychic damage and have Disadvantage on the next attack roll it makes before the end of its next turn.",
    higherLevels: "The damage increases by 1d6 when you reach levels 5 (2d6), 11 (3d6), and 17 (4d6).",
    concentration: false,
    ritual: false
  },
  {
    name: "Word of Radiance",
    level: 0,
    school: "Evocation",
    classes: ["Cleric"],
    castingTime: "Action",
    range: "Self (5-foot emanation)",
    components: "V, M (a sunburst token)",
    duration: "Instantaneous",
    description: "Burning radiance erupts from you in a 5-foot Emanation. Each creature of your choice that you can see in it must succeed on a Constitution saving throw or take 1d6 Radiant damage.",
    higherLevels: "The damage increases by 1d6 when you reach levels 5 (2d6), 11 (3d6), and 17 (4d6).",
    concentration: false,
    ritual: false
  },

  // 1st Level Spells
  {
    name: "Alarm",
    level: 1,
    school: "Abjuration",
    classes: ["Ranger", "Wizard"],
    castingTime: "1 minute",
    range: "30 feet",
    components: "V, S, M (a bell and silver wire)",
    duration: "8 hours",
    description: "You set an alarm against intrusion. Choose a door, a window, or an area within range that is no larger than a 20-foot Cube. Until the spell ends, an alarm alerts you whenever a creature touches or enters the warded area. When you cast the spell, you can designate creatures that won't set off the alarm. You also choose whether the alarm is audible or mental:\n\nAudible Alarm. The alarm produces the sound of a handbell for 10 seconds within 60 feet of the warded area.\n\nMental Alarm. You are alerted by a mental ping if you are within 1 mile of the warded area. This ping awakens you if you're asleep.",
    higherLevels: null,
    concentration: false,
    ritual: true
  },
  {
    name: "Bless",
    level: 1,
    school: "Enchantment",
    classes: ["Cleric", "Paladin"],
    castingTime: "Action",
    range: "30 feet",
    components: "V, S, M (a Holy Symbol worth 5+ GP)",
    duration: "Concentration, up to 1 minute",
    description: "You bless up to three creatures within range. Whenever a target makes an attack roll or a saving throw before the spell ends, the target adds 1d4 to the roll.",
    higherLevels: "You can target one additional creature for each slot level above 1.",
    concentration: true,
    ritual: false
  },
  {
    name: "Burning Hands",
    level: 1,
    school: "Evocation",
    classes: ["Sorcerer", "Wizard"],
    castingTime: "Action",
    range: "Self (15-foot cone)",
    components: "V, S",
    duration: "Instantaneous",
    description: "A thin sheet of flames shoots forth from you. Each creature in a 15-foot Cone makes a Dexterity saving throw, taking 3d6 Fire damage on a failed save or half as much damage on a successful one.\n\nFlammable objects in the Cone that aren't being worn or carried start burning.",
    higherLevels: "The damage increases by 1d6 for each slot level above 1.",
    concentration: false,
    ritual: false
  },
  {
    name: "Charm Person",
    level: 1,
    school: "Enchantment",
    classes: ["Bard", "Druid", "Sorcerer", "Warlock", "Wizard"],
    castingTime: "Action",
    range: "30 feet",
    components: "V, S",
    duration: "1 hour",
    description: "One Humanoid you can see within range makes a Wisdom saving throw. It does so with Advantage if you or your allies are fighting it. On a failed save, the target has the Charmed condition until the spell ends or until you or your allies damage it. The Charmed creature is Friendly to you. When the spell ends, the target knows it was Charmed by you.",
    higherLevels: "You can target one additional creature for each slot level above 1.",
    concentration: false,
    ritual: false
  },
  {
    name: "Chromatic Orb",
    level: 1,
    school: "Evocation",
    classes: ["Sorcerer", "Wizard"],
    castingTime: "Action",
    range: "90 feet",
    components: "V, S, M (a diamond worth 50+ GP)",
    duration: "Instantaneous",
    description: "You hurl an orb of energy at a target within range. Choose Acid, Cold, Fire, Lightning, Poison, or Thunder for the type of orb you create, and then make a ranged spell attack against the target. On a hit, the target takes 3d8 damage of the chosen type.\n\nIf you roll the same number on two or more of the d8s, the orb leaps to a different target of your choice within 30 feet of the target. Make an attack roll against the new target, and make a new damage roll. The orb can't leap again unless you cast the spell with a level 2+ spell slot.",
    higherLevels: "The damage increases by 1d8 for each slot level above 1, and the orb can leap a maximum number of times equal to the level of the slot expended.",
    concentration: false,
    ritual: false
  },
  {
    name: "Command",
    level: 1,
    school: "Enchantment",
    classes: ["Bard", "Cleric", "Paladin"],
    castingTime: "Action",
    range: "60 feet",
    components: "V",
    duration: "Instantaneous",
    description: "You speak a one-word command to a creature you can see within range. The target must succeed on a Wisdom saving throw or follow the command on its next turn. Choose the command from these options:\n\nApproach. The target moves toward you by the shortest and most direct route, ending its turn if it moves within 5 feet of you.\n\nDrop. The target drops whatever it is holding and then ends its turn.\n\nFlee. The target spends its turn moving away from you by the fastest available means.\n\nGrovel. The target has the Prone condition and then ends its turn.\n\nHalt. On its turn, the target doesn't move and takes no action or Bonus Action.",
    higherLevels: "You can affect one additional creature for each slot level above 1.",
    concentration: false,
    ritual: false
  },
  {
    name: "Comprehend Languages",
    level: 1,
    school: "Divination",
    classes: ["Bard", "Sorcerer", "Warlock", "Wizard"],
    castingTime: "Action",
    range: "Self",
    components: "V, S, M (a pinch of soot and salt)",
    duration: "1 hour",
    description: "For the duration, you understand the literal meaning of any language that you hear or see signed. You also understand any written language that you see, but you must be touching the surface on which the words are written. It takes about 1 minute to read one page of text. This spell doesn't decode symbols or secret messages.",
    higherLevels: null,
    concentration: false,
    ritual: true
  },
  {
    name: "Cure Wounds",
    level: 1,
    school: "Abjuration",
    classes: ["Bard", "Cleric", "Druid", "Paladin", "Ranger"],
    castingTime: "Action",
    range: "Touch",
    components: "V, S",
    duration: "Instantaneous",
    description: "A creature you touch regains a number of Hit Points equal to 2d8 plus your spellcasting ability modifier.",
    higherLevels: "The healing increases by 2d8 for each slot level above 1.",
    concentration: false,
    ritual: false
  },
  {
    name: "Detect Magic",
    level: 1,
    school: "Divination",
    classes: ["Bard", "Cleric", "Druid", "Paladin", "Ranger", "Sorcerer", "Warlock", "Wizard"],
    castingTime: "Action",
    range: "Self (30-foot radius)",
    components: "V, S",
    duration: "Concentration, up to 10 minutes",
    description: "For the duration, you sense the presence of magical effects within 30 feet of yourself. If you sense such effects, you can take the Magic action to see a faint aura around any visible creature or object in the area that bears the magic, and if an effect was created by a spell, you learn the spell's school of magic.\n\nThe spell can penetrate most barriers but is blocked by 1 foot of stone, 1 inch of common metal, a thin sheet of lead, or 3 feet of wood or dirt.",
    higherLevels: null,
    concentration: true,
    ritual: true
  },
  {
    name: "Disguise Self",
    level: 1,
    school: "Illusion",
    classes: ["Bard", "Sorcerer", "Wizard"],
    castingTime: "Action",
    range: "Self",
    components: "V, S",
    duration: "1 hour",
    description: "You make yourself—including your clothing, armor, weapons, and other belongings on your person—look different until the spell ends. You can seem up to 1 foot shorter or taller and can appear heavier or lighter. You must adopt a form that has the same basic arrangement of limbs as you have. Otherwise, the extent of the illusion is up to you.\n\nThe changes wrought by this spell fail to hold up to physical inspection. For example, if you use this spell to add a hat to your outfit, objects pass through the hat, and anyone who touches it would feel nothing.\n\nTo discern that you are disguised, a creature must take the Study action to inspect your appearance and succeed on an Intelligence (Investigation) check against your spell save DC.",
    higherLevels: null,
    concentration: false,
    ritual: false
  },
  {
    name: "Divine Favor",
    level: 1,
    school: "Transmutation",
    classes: ["Paladin"],
    castingTime: "Bonus Action",
    range: "Self",
    components: "V, S",
    duration: "1 minute",
    description: "Until the spell ends, your attacks with weapons deal an extra 1d4 Radiant damage on a hit.",
    higherLevels: null,
    concentration: false,
    ritual: false
  },
  {
    name: "Faerie Fire",
    level: 1,
    school: "Evocation",
    classes: ["Bard", "Druid"],
    castingTime: "Action",
    range: "60 feet",
    components: "V",
    duration: "Concentration, up to 1 minute",
    description: "Objects in a 20-foot Cube within range are outlined in blue, green, or violet light (your choice). Each creature in the Cube is also outlined if it fails a Dexterity saving throw. For the duration, objects and affected creatures shed Dim Light in a 10-foot radius and can't benefit from the Invisible condition.",
    higherLevels: null,
    concentration: true,
    ritual: false
  },
  {
    name: "Feather Fall",
    level: 1,
    school: "Transmutation",
    classes: ["Bard", "Sorcerer", "Wizard"],
    castingTime: "Reaction, which you take when you or a creature you can see within 60 feet of you falls",
    range: "60 feet",
    components: "V, M (a small feather or piece of down)",
    duration: "1 minute",
    description: "Choose up to five falling creatures within range. A falling creature's rate of descent slows to 60 feet per round until the spell ends. If a creature lands before the spell ends, the creature takes no damage from the fall, and the spell ends for that creature.",
    higherLevels: null,
    concentration: false,
    ritual: false
  },
  {
    name: "Find Familiar",
    level: 1,
    school: "Conjuration",
    classes: ["Wizard"],
    castingTime: "1 hour",
    range: "10 feet",
    components: "V, S, M (burning incense worth 10+ GP, which the spell consumes)",
    duration: "Instantaneous",
    description: "You gain the service of a familiar, a spirit that takes an animal form you choose: Bat, Cat, Frog, Hawk, Lizard, Octopus, Owl, Rat, Raven, Spider, Weasel, or another Beast that has a Challenge Rating of 0. Appearing in an unoccupied space within range, the familiar has the statistics of the chosen form, though it is a Celestial, Fey, or Fiend (your choice) instead of a Beast. Your familiar acts independently of you, but it obeys your commands.\n\nTelepathic Connection. While your familiar is within 100 feet of you, you can communicate with it telepathically. Additionally, as a Bonus Action, you can see through your familiar's eyes and hear what it hears until the start of your next turn, gaining the benefits of any special senses it has.\n\nCombat. The familiar is an ally to you and your allies. It rolls its own Initiative and acts on its own turn. A familiar can't attack, but it can take other actions as normal.\n\nDisappearance. When the familiar drops to 0 Hit Points, it disappears. It reappears after you cast this spell again. As a Magic action, you can temporarily dismiss the familiar to a pocket dimension. Alternatively, you can dismiss it forever. As a Magic action while it is temporarily dismissed, you can cause it to reappear in an unoccupied space within 30 feet of you. Whenever the familiar drops to 0 Hit Points or disappears into the pocket dimension, it leaves behind in its space anything it was wearing or carrying.",
    higherLevels: null,
    concentration: false,
    ritual: true
  },
  {
    name: "Fog Cloud",
    level: 1,
    school: "Conjuration",
    classes: ["Druid", "Ranger", "Sorcerer", "Wizard"],
    castingTime: "Action",
    range: "120 feet",
    components: "V, S",
    duration: "Concentration, up to 1 hour",
    description: "You create a 20-foot-radius Sphere of fog centered on a point within range. The Sphere is Heavily Obscured. It lasts for the duration or until a strong wind (such as one created by Gust of Wind) disperses it.",
    higherLevels: "The fog's radius increases by 20 feet for each slot level above 1.",
    concentration: true,
    ritual: false
  },
  {
    name: "Goodberry",
    level: 1,
    school: "Conjuration",
    classes: ["Druid", "Ranger"],
    castingTime: "Action",
    range: "Self",
    components: "V, S, M (a sprig of mistletoe)",
    duration: "24 hours",
    description: "Ten berries appear in your hand and are infused with magic for the duration. A creature can take a Bonus Action to eat one berry. Eating a berry restores 1 Hit Point, and the berry provides enough nourishment to sustain a creature for one day. Uneaten berries disappear when the spell ends.",
    higherLevels: null,
    concentration: false,
    ritual: false
  },
  {
    name: "Grease",
    level: 1,
    school: "Conjuration",
    classes: ["Sorcerer", "Wizard"],
    castingTime: "Action",
    range: "60 feet",
    components: "V, S, M (a bit of pork rind or butter)",
    duration: "1 minute",
    description: "Slick grease covers the ground in a 10-foot square centered on a point within range and turns it into Difficult Terrain for the duration.\n\nWhen the grease appears, each creature standing in its area must succeed on a Dexterity saving throw or have the Prone condition. A creature that enters the area or ends its turn there must also succeed on that save or fall Prone.",
    higherLevels: null,
    concentration: false,
    ritual: false
  },
  {
    name: "Guiding Bolt",
    level: 1,
    school: "Evocation",
    classes: ["Cleric"],
    castingTime: "Action",
    range: "120 feet",
    components: "V, S",
    duration: "1 round",
    description: "A flash of light streaks toward a creature of your choice within range. Make a ranged spell attack against the target. On a hit, the target takes 4d6 Radiant damage, and the next attack roll made against this target before the end of your next turn has Advantage.",
    higherLevels: "The damage increases by 1d6 for each slot level above 1.",
    concentration: false,
    ritual: false
  },
  {
    name: "Healing Word",
    level: 1,
    school: "Abjuration",
    classes: ["Bard", "Cleric", "Druid"],
    castingTime: "Bonus Action",
    range: "60 feet",
    components: "V",
    duration: "Instantaneous",
    description: "A creature of your choice that you can see within range regains Hit Points equal to 2d4 plus your spellcasting ability modifier.",
    higherLevels: "The healing increases by 2d4 for each slot level above 1.",
    concentration: false,
    ritual: false
  },
  {
    name: "Hellish Rebuke",
    level: 1,
    school: "Evocation",
    classes: ["Warlock"],
    castingTime: "Reaction, which you take in response to taking damage from a creature that you can see within 60 feet of yourself",
    range: "60 feet",
    components: "V, S",
    duration: "Instantaneous",
    description: "The creature that damaged you is momentarily surrounded by green flames. It makes a Dexterity saving throw, taking 2d10 Fire damage on a failed save or half as much damage on a successful one.",
    higherLevels: "The damage increases by 1d10 for each slot level above 1.",
    concentration: false,
    ritual: false
  },
  {
    name: "Heroism",
    level: 1,
    school: "Enchantment",
    classes: ["Bard", "Paladin"],
    castingTime: "Action",
    range: "Touch",
    components: "V, S",
    duration: "Concentration, up to 1 minute",
    description: "A willing creature you touch is imbued with bravery. Until the spell ends, the creature is immune to the Frightened condition and gains Temporary Hit Points equal to your spellcasting ability modifier at the start of each of its turns.",
    higherLevels: "You can target one additional creature for each slot level above 1.",
    concentration: true,
    ritual: false
  },
  {
    name: "Hex",
    level: 1,
    school: "Enchantment",
    classes: ["Warlock"],
    castingTime: "Bonus Action",
    range: "90 feet",
    components: "V, S, M (the petrified eye of a newt)",
    duration: "Concentration, up to 1 hour",
    description: "You place a curse on a creature that you can see within range. Until the spell ends, you deal an extra 1d6 Necrotic damage to the target whenever you hit it with an attack roll. Also, choose one ability when you cast the spell. The target has Disadvantage on ability checks made with the chosen ability.\n\nIf the target drops to 0 Hit Points before this spell ends, you can take a Bonus Action on a later turn to curse a new creature.",
    higherLevels: "The spell's duration is 8 hours when cast with a level 3–4 spell slot and 24 hours when cast with a level 5+ spell slot.",
    concentration: true,
    ritual: false
  },
  {
    name: "Hunter's Mark",
    level: 1,
    school: "Divination",
    classes: ["Ranger"],
    castingTime: "Bonus Action",
    range: "90 feet",
    components: "V",
    duration: "Concentration, up to 1 hour",
    description: "You magically mark one creature you can see within range as your quarry. Until the spell ends, you deal an extra 1d6 Force damage to the target whenever you hit it with an attack roll. You also have Advantage on any Wisdom (Perception or Survival) check you make to find it.\n\nIf the target drops to 0 Hit Points before this spell ends, you can take a Bonus Action to mark a new creature.",
    higherLevels: "The spell's duration is 8 hours when cast with a level 3–4 spell slot and 24 hours when cast with a level 5+ spell slot.",
    concentration: true,
    ritual: false
  },
  {
    name: "Identify",
    level: 1,
    school: "Divination",
    classes: ["Bard", "Wizard"],
    castingTime: "1 minute",
    range: "Touch",
    components: "V, S, M (a pearl worth 100+ GP)",
    duration: "Instantaneous",
    description: "You touch an object throughout the spell's casting. If the object is a magic item or some other magical object, you learn its properties and how to use them, whether it requires Attunement, and how many charges it has, if any. You learn whether any ongoing spells are affecting the item and what they are. If the item was created by a spell, you learn that spell.\n\nIf you instead touch a creature throughout the casting, you learn which ongoing spells, if any, are currently affecting it.",
    higherLevels: null,
    concentration: false,
    ritual: true
  },
  {
    name: "Inflict Wounds",
    level: 1,
    school: "Necromancy",
    classes: ["Cleric"],
    castingTime: "Action",
    range: "Touch",
    components: "V, S",
    duration: "Instantaneous",
    description: "A creature you touch makes a Constitution saving throw, taking 2d10 Necrotic damage on a failed save or half as much damage on a successful one.",
    higherLevels: "The damage increases by 1d10 for each slot level above 1.",
    concentration: false,
    ritual: false
  },
  {
    name: "Jump",
    level: 1,
    school: "Transmutation",
    classes: ["Druid", "Ranger", "Sorcerer", "Wizard"],
    castingTime: "Bonus Action",
    range: "Touch",
    components: "V, S, M (a grasshopper's hind leg)",
    duration: "1 minute",
    description: "You touch a willing creature. Once on each of its turns until the spell ends, that creature can jump up to 30 feet by spending only 10 feet of movement.",
    higherLevels: null,
    concentration: false,
    ritual: false
  },
  {
    name: "Longstrider",
    level: 1,
    school: "Transmutation",
    classes: ["Bard", "Druid", "Ranger", "Wizard"],
    castingTime: "Action",
    range: "Touch",
    components: "V, S, M (a pinch of dirt)",
    duration: "1 hour",
    description: "You touch a creature. The target's Speed increases by 10 feet until the spell ends.",
    higherLevels: "You can target one additional creature for each slot level above 1.",
    concentration: false,
    ritual: false
  },
  {
    name: "Mage Armor",
    level: 1,
    school: "Abjuration",
    classes: ["Sorcerer", "Wizard"],
    castingTime: "Action",
    range: "Touch",
    components: "V, S, M (a piece of cured leather)",
    duration: "8 hours",
    description: "You touch a willing creature who isn't wearing armor. Until the spell ends, the target's base AC becomes 13 plus its Dexterity modifier. The spell ends early if the target dons armor.",
    higherLevels: null,
    concentration: false,
    ritual: false
  },
  {
    name: "Magic Missile",
    level: 1,
    school: "Evocation",
    classes: ["Sorcerer", "Wizard"],
    castingTime: "Action",
    range: "120 feet",
    components: "V, S",
    duration: "Instantaneous",
    description: "You create three glowing darts of magical force. Each dart hits a creature of your choice that you can see within range. A dart deals 1d4 + 1 Force damage to its target. The darts all strike simultaneously, and you can direct them to hit one creature or several.",
    higherLevels: "The spell creates one more dart for each slot level above 1.",
    concentration: false,
    ritual: false
  },
  {
    name: "Protection from Evil and Good",
    level: 1,
    school: "Abjuration",
    classes: ["Cleric", "Druid", "Paladin", "Warlock", "Wizard"],
    castingTime: "Action",
    range: "Touch",
    components: "V, S, M (a flask of Holy Water worth 25+ GP, which the spell consumes)",
    duration: "Concentration, up to 10 minutes",
    description: "Until the spell ends, one willing creature you touch is protected against creatures that are Aberrations, Celestials, Elementals, Fey, Fiends, or Undead. The protection grants several benefits. Creatures of those types have Disadvantage on attack rolls against the target. The target also can't be possessed by or gain the Charmed or Frightened condition from them. If the target is already possessed, Charmed, or Frightened by such a creature, the target has Advantage on any new saving throw against the relevant effect.",
    higherLevels: null,
    concentration: true,
    ritual: false
  },
  {
    name: "Shield",
    level: 1,
    school: "Abjuration",
    classes: ["Sorcerer", "Wizard"],
    castingTime: "Reaction, which you take when you are hit by an attack roll or targeted by the Magic Missile spell",
    range: "Self",
    components: "V, S",
    duration: "1 round",
    description: "An imperceptible barrier of magical force protects you. Until the start of your next turn, you have a +5 bonus to AC, including against the triggering attack, and you take no damage from Magic Missile.",
    higherLevels: null,
    concentration: false,
    ritual: false
  },
  {
    name: "Shield of Faith",
    level: 1,
    school: "Abjuration",
    classes: ["Cleric", "Paladin"],
    castingTime: "Bonus Action",
    range: "60 feet",
    components: "V, S, M (a prayer scroll)",
    duration: "Concentration, up to 10 minutes",
    description: "A shimmering field appears and surrounds a creature of your choice within range, granting it a +2 bonus to AC for the duration.",
    higherLevels: null,
    concentration: true,
    ritual: false
  },
  {
    name: "Sleep",
    level: 1,
    school: "Enchantment",
    classes: ["Bard", "Sorcerer", "Wizard"],
    castingTime: "Action",
    range: "60 feet",
    components: "V, S, M (a pinch of sand or rose petals)",
    duration: "Concentration, up to 1 minute",
    description: "Each creature of your choice in a 5-foot-radius Sphere centered on a point within range must succeed on a Wisdom saving throw or have the Incapacitated condition until the spell ends, the sleeper takes damage, or someone takes an action to shake the sleeper awake.",
    higherLevels: "The Sphere's radius increases by 5 feet for each slot level above 1.",
    concentration: true,
    ritual: false
  },
  {
    name: "Speak with Animals",
    level: 1,
    school: "Divination",
    classes: ["Bard", "Druid", "Ranger"],
    castingTime: "Action",
    range: "Self",
    components: "V, S",
    duration: "10 minutes",
    description: "For the duration, you can comprehend and verbally communicate with Beasts, and you can use any of the Influence action's skill options with them.\n\nMost Beasts have little to say about topics that don't pertain to survival or their environment, but at minimum, a Beast can give you information about nearby locations and monsters, including whatever it has perceived within the past day.",
    higherLevels: null,
    concentration: false,
    ritual: true
  },
  {
    name: "Thunderwave",
    level: 1,
    school: "Evocation",
    classes: ["Bard", "Druid", "Sorcerer", "Wizard"],
    castingTime: "Action",
    range: "Self (15-foot cube)",
    components: "V, S",
    duration: "Instantaneous",
    description: "A wave of thunderous force sweeps out from you. Each creature in a 15-foot Cube originating from you makes a Constitution saving throw. On a failed save, a creature takes 2d8 Thunder damage and is pushed 10 feet away from you. On a successful save, a creature takes half as much damage only.\n\nIn addition, unsecured objects that are completely within the area are pushed 10 feet away from you, and a thunderous boom is audible within 300 feet.",
    higherLevels: "The damage increases by 1d8 for each slot level above 1.",
    concentration: false,
    ritual: false
  },
  {
    name: "Witch Bolt",
    level: 1,
    school: "Evocation",
    classes: ["Sorcerer", "Warlock", "Wizard"],
    castingTime: "Action",
    range: "60 feet",
    components: "V, S, M (a twig struck by lightning)",
    duration: "Concentration, up to 1 minute",
    description: "A beam of crackling energy lances toward a creature within range, forming a sustained arc of lightning between you and the target. Make a ranged spell attack against it. On a hit, the target takes 2d12 Lightning damage.\n\nOn each of your subsequent turns, you can take a Bonus Action to deal 1d12 Lightning damage to the target automatically if it is within range. The spell ends if the target is ever outside the spell's range or if it has Total Cover from you.",
    higherLevels: "The initial damage increases by 1d12 for each slot level above 1.",
    concentration: true,
    ritual: false
  },

  // 2nd Level Spells
  {
    name: "Aid",
    level: 2,
    school: "Abjuration",
    classes: ["Bard", "Cleric", "Druid", "Paladin", "Ranger"],
    castingTime: "Action",
    range: "30 feet",
    components: "V, S, M (a strip of white cloth)",
    duration: "8 hours",
    description: "Choose up to three creatures within range. Each target's Hit Point maximum and current Hit Points increase by 5 for the duration.",
    higherLevels: "Each target's Hit Points increase by 5 for each slot level above 2.",
    concentration: false,
    ritual: false
  },
  {
    name: "Blindness/Deafness",
    level: 2,
    school: "Transmutation",
    classes: ["Bard", "Cleric", "Sorcerer", "Wizard"],
    castingTime: "Action",
    range: "120 feet",
    components: "V",
    duration: "1 minute",
    description: "One creature that you can see within range must succeed on a Constitution saving throw, or it has the Blinded or Deafened condition (your choice) for the duration. At the end of each of its turns, the target repeats the save, ending the spell on itself on a success.",
    higherLevels: "You can target one additional creature for each slot level above 2.",
    concentration: false,
    ritual: false
  },
  {
    name: "Blur",
    level: 2,
    school: "Illusion",
    classes: ["Sorcerer", "Wizard"],
    castingTime: "Action",
    range: "Self",
    components: "V",
    duration: "Concentration, up to 1 minute",
    description: "Your body becomes blurred. For the duration, any creature has Disadvantage on attack rolls against you. An attacker is immune to this effect if it perceives you with Blindsight or Truesight or doesn't rely on sight.",
    higherLevels: null,
    concentration: true,
    ritual: false
  },
  {
    name: "Calm Emotions",
    level: 2,
    school: "Enchantment",
    classes: ["Bard", "Cleric"],
    castingTime: "Action",
    range: "60 feet",
    components: "V, S",
    duration: "Concentration, up to 1 minute",
    description: "Each Humanoid in a 20-foot-radius Sphere centered on a point you choose within range must succeed on a Charisma saving throw or be affected by one of the following effects (choose for each creature):\n\nEnd Effect. You suppress any ongoing effect causing the target to have the Charmed or Frightened condition.\n\nMake Indifferent. You make the target Indifferent toward creatures of your choice that it was Hostile toward. This indifference ends if the target takes damage or witnesses its allies taking damage. When the spell ends, the creature's attitude returns to normal.",
    higherLevels: null,
    concentration: true,
    ritual: false
  },
  {
    name: "Darkness",
    level: 2,
    school: "Evocation",
    classes: ["Sorcerer", "Warlock", "Wizard"],
    castingTime: "Action",
    range: "60 feet",
    components: "V, M (bat fur and a piece of coal)",
    duration: "Concentration, up to 10 minutes",
    description: "For the duration, magical Darkness spreads from a point within range and fills a 15-foot-radius Sphere. Darkvision can't see through it, and nonmagical light can't illuminate it.\n\nAlternatively, you cast the spell on an object that isn't being worn or carried, causing the Darkness to fill a 15-foot Emanation originating from that object. Covering that object with something opaque, such as a bowl or helm, blocks the Darkness.\n\nIf any of this spell's area overlaps with an area of Bright Light or Dim Light created by a spell of level 2 or lower, that other spell is dispelled.",
    higherLevels: null,
    concentration: true,
    ritual: false
  },
  {
    name: "Darkvision",
    level: 2,
    school: "Transmutation",
    classes: ["Druid", "Ranger", "Sorcerer", "Wizard"],
    castingTime: "Action",
    range: "Touch",
    components: "V, S, M (a dried carrot)",
    duration: "8 hours",
    description: "You touch a willing creature to grant it Darkvision with a range of 150 feet for the duration.",
    higherLevels: null,
    concentration: false,
    ritual: false
  },
  {
    name: "Enhance Ability",
    level: 2,
    school: "Transmutation",
    classes: ["Bard", "Cleric", "Druid", "Ranger", "Sorcerer", "Wizard"],
    castingTime: "Action",
    range: "Touch",
    components: "V, S, M (fur or a feather)",
    duration: "Concentration, up to 1 hour",
    description: "You touch a creature and choose Strength, Dexterity, Constitution, Intelligence, Wisdom, or Charisma. For the duration, the target has Advantage on ability checks using the chosen ability.",
    higherLevels: "You can target one additional creature for each slot level above 2. You can choose a different ability for each target.",
    concentration: true,
    ritual: false
  },
  {
    name: "Enlarge/Reduce",
    level: 2,
    school: "Transmutation",
    classes: ["Bard", "Druid", "Sorcerer", "Wizard"],
    castingTime: "Action",
    range: "30 feet",
    components: "V, S, M (a pinch of powdered iron)",
    duration: "Concentration, up to 1 minute",
    description: "For the duration, a creature or an object you can see within range is magically resized. Choose either the Enlarge or the Reduce effect.\n\nEnlarge. The target's size increases by one category—from Medium to Large, for example. If there isn't enough room for the target to increase in size, the target attains the maximum possible size in the space available. Until the spell ends, the target has Advantage on Strength checks and Strength saving throws, and the target's attacks with its body or weapons deal 1d4 extra damage.\n\nReduce. The target's size decreases by one category—from Medium to Small, for example. Until the spell ends, the target has Disadvantage on Strength checks and Strength saving throws, and the target's attacks with its body or weapons deal 1d4 less damage (this can't reduce the damage below 1).\n\nAn unwilling creature can make a Constitution saving throw. On a successful save, the spell has no effect.",
    higherLevels: null,
    concentration: true,
    ritual: false
  },
  {
    name: "Flaming Sphere",
    level: 2,
    school: "Conjuration",
    classes: ["Druid", "Sorcerer", "Wizard"],
    castingTime: "Action",
    range: "60 feet",
    components: "V, S, M (a ball of wax)",
    duration: "Concentration, up to 1 minute",
    description: "You create a 5-foot-diameter Sphere of fire in an unoccupied space on the ground within range. It lasts for the duration. Any creature that ends its turn within 5 feet of the Sphere makes a Dexterity saving throw, taking 2d6 Fire damage on a failed save or half as much damage on a successful one.\n\nAs a Bonus Action, you can move the Sphere up to 30 feet, rolling it along the ground. If you move the Sphere into a creature's space, that creature makes the save against the Sphere, and the Sphere stops moving for the turn.\n\nWhen you move the Sphere, you can direct it over barriers up to 5 feet tall and jump it across pits up to 10 feet wide. The Sphere ignites flammable objects that aren't being worn or carried, and it sheds Bright Light in a 20-foot radius and Dim Light for an additional 20 feet.",
    higherLevels: "The damage increases by 1d6 for each slot level above 2.",
    concentration: true,
    ritual: false
  },
  {
    name: "Hold Person",
    level: 2,
    school: "Enchantment",
    classes: ["Bard", "Cleric", "Druid", "Sorcerer", "Warlock", "Wizard"],
    castingTime: "Action",
    range: "60 feet",
    components: "V, S, M (a straight piece of iron)",
    duration: "Concentration, up to 1 minute",
    description: "Choose a Humanoid that you can see within range. The target must succeed on a Wisdom saving throw or have the Paralyzed condition for the duration. At the end of each of its turns, the target repeats the save, ending the spell on itself on a success.",
    higherLevels: "You can target one additional Humanoid for each slot level above 2.",
    concentration: true,
    ritual: false
  },
  {
    name: "Invisibility",
    level: 2,
    school: "Illusion",
    classes: ["Bard", "Sorcerer", "Warlock", "Wizard"],
    castingTime: "Action",
    range: "Touch",
    components: "V, S, M (an eyelash in gum arabic)",
    duration: "Concentration, up to 1 hour",
    description: "A creature you touch has the Invisible condition until the spell ends. The spell ends early immediately after the target makes an attack roll, deals damage, or casts a spell.",
    higherLevels: "You can target one additional creature for each slot level above 2.",
    concentration: true,
    ritual: false
  },
  {
    name: "Knock",
    level: 2,
    school: "Transmutation",
    classes: ["Bard", "Sorcerer", "Wizard"],
    castingTime: "Action",
    range: "60 feet",
    components: "V",
    duration: "Instantaneous",
    description: "Choose an object that you can see within range. The object can be a door, a container, or an opening covered by a mundane lock, or it can be an object that is shut or fastened with Arcane Lock.\n\nA target that is held shut by a mundane lock, stuck, or barred becomes unlocked, unstuck, or unbarred. If the target has multiple locks, only one of them is unlocked by the spell. An Arcane Lock on a target is suppressed for 10 minutes.\n\nWhen you cast the spell, a loud knock, audible from as far away as 300 feet, emanates from the target.",
    higherLevels: null,
    concentration: false,
    ritual: false
  },
  {
    name: "Lesser Restoration",
    level: 2,
    school: "Abjuration",
    classes: ["Bard", "Cleric", "Druid", "Paladin", "Ranger"],
    castingTime: "Bonus Action",
    range: "Touch",
    components: "V, S",
    duration: "Instantaneous",
    description: "You touch a creature and end one condition on it: Blinded, Deafened, Paralyzed, or Poisoned.",
    higherLevels: null,
    concentration: false,
    ritual: false
  },
  {
    name: "Levitate",
    level: 2,
    school: "Transmutation",
    classes: ["Sorcerer", "Wizard"],
    castingTime: "Action",
    range: "60 feet",
    components: "V, S, M (a metal spring)",
    duration: "Concentration, up to 10 minutes",
    description: "One creature or loose object of your choice that you can see within range rises vertically up to 20 feet and remains suspended there for the duration. The spell can levitate an object that weighs up to 500 pounds. An unwilling creature that succeeds on a Constitution saving throw is unaffected.\n\nThe target can move only by pushing or pulling against a fixed object or surface within reach (such as a wall or ceiling), which allows it to move as if it were climbing. You can change the target's altitude by up to 20 feet in either direction on your turn. If you are the target, you can move up or down as part of your move.",
    higherLevels: null,
    concentration: true,
    ritual: false
  },
  {
    name: "Magic Weapon",
    level: 2,
    school: "Transmutation",
    classes: ["Paladin", "Ranger", "Sorcerer", "Wizard"],
    castingTime: "Bonus Action",
    range: "Touch",
    components: "V, S",
    duration: "1 hour",
    description: "You touch a nonmagical weapon. Until the spell ends, that weapon becomes a +1 magic weapon.",
    higherLevels: "The bonus increases to +2 when you use a level 4 slot, and the bonus increases to +3 when you use a level 6+ slot.",
    concentration: false,
    ritual: false
  },
  {
    name: "Mirror Image",
    level: 2,
    school: "Illusion",
    classes: ["Bard", "Sorcerer", "Warlock", "Wizard"],
    castingTime: "Action",
    range: "Self",
    components: "V, S",
    duration: "1 minute",
    description: "Three illusory duplicates of yourself appear in your space. Until the spell ends, the duplicates move with you and mimic your actions, shifting position so it's impossible to track which image is real.\n\nEach time a creature hits you with an attack roll during the spell's duration, roll a d6 for each of your remaining duplicates. If any of the d6s rolls a 3 or higher, one of the duplicates is hit instead of you, and the duplicate is destroyed. The duplicates otherwise ignore all other damage and effects. The spell ends when all three duplicates are destroyed.\n\nA creature is unaffected by this spell if it has the Blinded condition, has Blindsight, or has Truesight.",
    higherLevels: null,
    concentration: false,
    ritual: false
  },
  {
    name: "Misty Step",
    level: 2,
    school: "Conjuration",
    classes: ["Sorcerer", "Warlock", "Wizard"],
    castingTime: "Bonus Action",
    range: "Self",
    components: "V",
    duration: "Instantaneous",
    description: "Briefly surrounded by silvery mist, you teleport up to 30 feet to an unoccupied space you can see.",
    higherLevels: null,
    concentration: false,
    ritual: false
  },
  {
    name: "Moonbeam",
    level: 2,
    school: "Evocation",
    classes: ["Druid"],
    castingTime: "Action",
    range: "120 feet",
    components: "V, S, M (a moonseed leaf)",
    duration: "Concentration, up to 1 minute",
    description: "A silvery beam of pale light shines down in a 5-foot-radius, 40-foot-high Cylinder centered on a point within range. Until the spell ends, Dim Light fills the Cylinder.\n\nWhen a creature enters the spell's area for the first time on a turn or starts its turn there, it makes a Constitution saving throw, taking 2d10 Radiant damage on a failed save or half as much damage on a successful one.\n\nOn your later turns, you can take a Magic action to move the Cylinder up to 60 feet.",
    higherLevels: "The damage increases by 1d10 for each slot level above 2.",
    concentration: true,
    ritual: false
  },
  {
    name: "Pass without Trace",
    level: 2,
    school: "Abjuration",
    classes: ["Druid", "Ranger"],
    castingTime: "Action",
    range: "Self",
    components: "V, S, M (ashes from burned mistletoe)",
    duration: "Concentration, up to 1 hour",
    description: "You radiate a veil of shadow and silence that makes you and your companions difficult to detect. For the duration, each creature you choose within 30 feet of you (including yourself) has a +10 bonus to Dexterity (Stealth) checks and can't be tracked except by magical means. A creature that receives this bonus leaves behind no tracks or other traces of its passage.",
    higherLevels: null,
    concentration: true,
    ritual: false
  },
  {
    name: "Prayer of Healing",
    level: 2,
    school: "Abjuration",
    classes: ["Cleric", "Paladin"],
    castingTime: "10 minutes",
    range: "30 feet",
    components: "V",
    duration: "Instantaneous",
    description: "Up to five creatures of your choice who remain within range for the spell's entire casting gain the benefits of a Short Rest and also regain 2d8 Hit Points. A creature can't be affected by this spell again until that creature finishes a Long Rest.",
    higherLevels: "The healing increases by 1d8 for each slot level above 2.",
    concentration: false,
    ritual: false
  },
  {
    name: "Scorching Ray",
    level: 2,
    school: "Evocation",
    classes: ["Sorcerer", "Wizard"],
    castingTime: "Action",
    range: "120 feet",
    components: "V, S",
    duration: "Instantaneous",
    description: "You hurl three fiery rays. You can hurl them at one target within range or at several. Make a ranged spell attack for each ray. On a hit, the target takes 2d6 Fire damage.",
    higherLevels: "You create one additional ray for each slot level above 2.",
    concentration: false,
    ritual: false
  },
  {
    name: "See Invisibility",
    level: 2,
    school: "Divination",
    classes: ["Bard", "Sorcerer", "Wizard"],
    castingTime: "Action",
    range: "Self",
    components: "V, S, M (a pinch of talc)",
    duration: "1 hour",
    description: "For the duration, you see creatures and objects that have the Invisible condition as if they were visible, and you can see into the Ethereal Plane. Ethereal creatures and objects appear ghostly.",
    higherLevels: null,
    concentration: false,
    ritual: false
  },
  {
    name: "Shatter",
    level: 2,
    school: "Evocation",
    classes: ["Bard", "Sorcerer", "Warlock", "Wizard"],
    castingTime: "Action",
    range: "60 feet",
    components: "V, S, M (a chip of mica)",
    duration: "Instantaneous",
    description: "A loud noise erupts from a point of your choice within range. Each creature in a 10-foot-radius Sphere centered there makes a Constitution saving throw, taking 3d8 Thunder damage on a failed save or half as much damage on a successful one. A creature made of inorganic material such as stone, crystal, or metal has Disadvantage on this save.\n\nA nonmagical object that isn't being worn or carried also takes the damage if it's in the spell's area.",
    higherLevels: "The damage increases by 1d8 for each slot level above 2.",
    concentration: false,
    ritual: false
  },
  {
    name: "Silence",
    level: 2,
    school: "Illusion",
    classes: ["Bard", "Cleric", "Ranger"],
    castingTime: "Action",
    range: "120 feet",
    components: "V, S",
    duration: "Concentration, up to 10 minutes",
    description: "For the duration, no sound can be created within or pass through a 20-foot-radius Sphere centered on a point you choose within range. Any creature or object entirely inside the Sphere has Immunity to Thunder damage, and creatures have the Deafened condition while entirely inside it. Casting a spell that includes a Verbal component is impossible there.",
    higherLevels: null,
    concentration: true,
    ritual: true
  },
  {
    name: "Spider Climb",
    level: 2,
    school: "Transmutation",
    classes: ["Sorcerer", "Warlock", "Wizard"],
    castingTime: "Action",
    range: "Touch",
    components: "V, S, M (a drop of bitumen and a spider)",
    duration: "Concentration, up to 1 hour",
    description: "Until the spell ends, one willing creature you touch gains the ability to move up, down, and across vertical surfaces and along ceilings, while leaving its hands free. The target also gains a Climb Speed equal to its Speed.",
    higherLevels: null,
    concentration: true,
    ritual: false
  },
  {
    name: "Spiritual Weapon",
    level: 2,
    school: "Evocation",
    classes: ["Cleric"],
    castingTime: "Bonus Action",
    range: "60 feet",
    components: "V, S",
    duration: "1 minute",
    description: "You create a floating, spectral force that resembles a weapon of your choice and lasts for the duration. The force appears within range in a space of your choice, and you can immediately make one melee spell attack against one creature within 5 feet of the force. On a hit, the target takes Force damage equal to 1d8 plus your spellcasting ability modifier.\n\nAs a Bonus Action on your later turns, you can move the force up to 20 feet and repeat the attack against a creature within 5 feet of it.",
    higherLevels: "The damage increases by 1d8 for every slot level above 2.",
    concentration: false,
    ritual: false
  },
  {
    name: "Suggestion",
    level: 2,
    school: "Enchantment",
    classes: ["Bard", "Sorcerer", "Warlock", "Wizard"],
    castingTime: "Action",
    range: "30 feet",
    components: "V, M (a drop of honey)",
    duration: "Concentration, up to 8 hours",
    description: "You suggest a course of activity—described in no more than 25 words—to one creature you can see within range that can hear and understand you. The suggestion must sound achievable and not involve anything that would obviously deal damage to the target or its allies. For example, you could say, \"Fetch the key to the cult's treasure vault, and give the key to me.\" Or you could say, \"Stop fighting, leave this library, and don't return.\"\n\nThe target must succeed on a Wisdom saving throw or have the Charmed condition for the duration or until you or your allies deal damage to the target. The Charmed target pursues the suggestion to the best of its ability. The suggested activity can continue for the entire duration, but if the suggested activity can be completed in a shorter time, the spell ends for the target upon completing it.",
    higherLevels: null,
    concentration: true,
    ritual: false
  },
  {
    name: "Web",
    level: 2,
    school: "Conjuration",
    classes: ["Sorcerer", "Wizard"],
    castingTime: "Action",
    range: "60 feet",
    components: "V, S, M (a bit of spiderweb)",
    duration: "Concentration, up to 1 hour",
    description: "You conjure a mass of sticky webbing at a point within range. The webs fill a 20-foot Cube there for the duration. The webs are Difficult Terrain, and the area within them is Lightly Obscured.\n\nIf the webs aren't anchored between two solid masses (such as walls or trees) or layered across a floor, wall, or ceiling, the web collapses on itself, and the spell ends at the start of your next turn. Webs layered over a flat surface have a depth of 5 feet.\n\nThe first time a creature enters the webs on a turn or starts its turn there, it must succeed on a Dexterity saving throw or have the Restrained condition while in the webs or until it breaks free.\n\nA creature Restrained by the webs can take an action to make a Strength (Athletics) check against your spell save DC. If it succeeds, it is no longer Restrained.\n\nThe webs are flammable. Any 5-foot Cube of webs exposed to fire burns away in 1 round, dealing 2d4 Fire damage to any creature that starts its turn in the fire.",
    higherLevels: null,
    concentration: true,
    ritual: false
  },

  // 3rd Level Spells
  {
    name: "Counterspell",
    level: 3,
    school: "Abjuration",
    classes: ["Sorcerer", "Warlock", "Wizard"],
    castingTime: "Reaction, which you take when you see a creature within 60 feet of yourself casting a spell with a Verbal, Somatic, or Material component",
    range: "60 feet",
    components: "S",
    duration: "Instantaneous",
    description: "You attempt to interrupt a creature in the process of casting a spell. The creature makes a Constitution saving throw. On a failed save, the spell dissipates with no effect, and the action, Bonus Action, or Reaction used to cast it is wasted. If that spell was cast with a spell slot, the slot isn't expended.",
    higherLevels: null,
    concentration: false,
    ritual: false
  },
  {
    name: "Dispel Magic",
    level: 3,
    school: "Abjuration",
    classes: ["Bard", "Cleric", "Druid", "Paladin", "Sorcerer", "Warlock", "Wizard"],
    castingTime: "Action",
    range: "120 feet",
    components: "V, S",
    duration: "Instantaneous",
    description: "Choose one creature, object, or magical effect within range. Any ongoing spell of level 3 or lower on the target ends. For each ongoing spell of level 4 or higher on the target, make an ability check using your spellcasting ability (DC 10 plus that spell's level). On a successful check, the spell ends.",
    higherLevels: "You automatically end a spell on the target if the spell's level is equal to or less than the level of the spell slot you used.",
    concentration: false,
    ritual: false
  },
  {
    name: "Fireball",
    level: 3,
    school: "Evocation",
    classes: ["Sorcerer", "Wizard"],
    castingTime: "Action",
    range: "150 feet",
    components: "V, S, M (a ball of bat guano and sulfur)",
    duration: "Instantaneous",
    description: "A bright streak flashes from you to a point you choose within range and then blossoms with a low roar into a fiery explosion. Each creature in a 20-foot-radius Sphere centered on that point makes a Dexterity saving throw, taking 8d6 Fire damage on a failed save or half as much damage on a successful one.\n\nFlammable objects in the area that aren't being worn or carried start burning.",
    higherLevels: "The damage increases by 1d6 for each slot level above 3.",
    concentration: false,
    ritual: false
  },
  {
    name: "Fly",
    level: 3,
    school: "Transmutation",
    classes: ["Sorcerer", "Warlock", "Wizard"],
    castingTime: "Action",
    range: "Touch",
    components: "V, S, M (a feather)",
    duration: "Concentration, up to 10 minutes",
    description: "You touch a willing creature. The target gains a Fly Speed of 60 feet for the duration. When the spell ends, the target falls if it is still aloft unless it can stop the fall.",
    higherLevels: "You can target one additional creature for each slot level above 3.",
    concentration: true,
    ritual: false
  },
  {
    name: "Haste",
    level: 3,
    school: "Transmutation",
    classes: ["Sorcerer", "Wizard"],
    castingTime: "Action",
    range: "30 feet",
    components: "V, S, M (a shaving of licorice root)",
    duration: "Concentration, up to 1 minute",
    description: "Choose a willing creature that you can see within range. Until the spell ends, the target's Speed is doubled, it gains a +2 bonus to AC, it has Advantage on Dexterity saving throws, and it gains an additional action on each of its turns. That action can be used to take only the Attack (one attack only), Dash, Disengage, Hide, or Utilize action.\n\nWhen the spell ends, the target is Incapacitated and has a Speed of 0 until the end of its next turn, as a wave of lethargy washes over it.",
    higherLevels: null,
    concentration: true,
    ritual: false
  },
  {
    name: "Hypnotic Pattern",
    level: 3,
    school: "Illusion",
    classes: ["Bard", "Sorcerer", "Warlock", "Wizard"],
    castingTime: "Action",
    range: "120 feet",
    components: "S, M (a pinch of confetti)",
    duration: "Concentration, up to 1 minute",
    description: "You create a twisting pattern of colors in a 30-foot Cube within range. The pattern appears for a moment and vanishes. Each creature in the area who can see the pattern must succeed on a Wisdom saving throw or have the Charmed condition for the duration. While Charmed, the creature has the Incapacitated condition and a Speed of 0.\n\nThe spell ends for an affected creature if it takes any damage or if someone else uses an action to shake the creature out of its stupor.",
    higherLevels: null,
    concentration: true,
    ritual: false
  },
  {
    name: "Lightning Bolt",
    level: 3,
    school: "Evocation",
    classes: ["Sorcerer", "Wizard"],
    castingTime: "Action",
    range: "Self (100-foot line)",
    components: "V, S, M (a bit of fur and a crystal rod)",
    duration: "Instantaneous",
    description: "A stroke of lightning forming a 100-foot-long, 5-foot-wide Line blasts out from you in a direction you choose. Each creature in the Line makes a Dexterity saving throw, taking 8d6 Lightning damage on a failed save or half as much damage on a successful one.",
    higherLevels: "The damage increases by 1d6 for each slot level above 3.",
    concentration: false,
    ritual: false
  },
  {
    name: "Major Image",
    level: 3,
    school: "Illusion",
    classes: ["Bard", "Sorcerer", "Warlock", "Wizard"],
    castingTime: "Action",
    range: "120 feet",
    components: "V, S, M (a bit of fleece)",
    duration: "Concentration, up to 10 minutes",
    description: "You create the image of an object, a creature, or some other visible phenomenon that is no larger than a 20-foot Cube. The image appears at a spot that you can see within range and lasts for the duration. It seems real, including sounds, smells, and temperature appropriate to the thing depicted, but it can't deal damage or cause conditions.\n\nAs long as you are within range of the illusion, you can take a Magic action to cause the image to move to any other spot within range. As the image changes location, you can alter its appearance so that its movements appear natural for the image.\n\nPhysical interaction with the image reveals it to be an illusion, since things can pass through it. A creature that takes a Study action to examine the image can determine that it is an illusion with a successful Intelligence (Investigation) check against your spell save DC. If a creature discerns the illusion for what it is, the creature can see through the image, and its other sensory qualities become faint to the creature.",
    higherLevels: "The spell lasts until dispelled, without requiring Concentration, if cast with a level 6+ spell slot.",
    concentration: true,
    ritual: false
  },
  {
    name: "Mass Healing Word",
    level: 3,
    school: "Abjuration",
    classes: ["Bard", "Cleric"],
    castingTime: "Bonus Action",
    range: "60 feet",
    components: "V",
    duration: "Instantaneous",
    description: "Up to six creatures of your choice that you can see within range regain Hit Points equal to 2d4 plus your spellcasting ability modifier.",
    higherLevels: "The healing increases by 1d4 for each slot level above 3.",
    concentration: false,
    ritual: false
  },
  {
    name: "Revivify",
    level: 3,
    school: "Necromancy",
    classes: ["Cleric", "Druid", "Paladin", "Ranger"],
    castingTime: "Action",
    range: "Touch",
    components: "V, S, M (a diamond worth 300+ GP, which the spell consumes)",
    duration: "Instantaneous",
    description: "You touch a creature that has died within the last minute. That creature revives with 1 Hit Point. This spell can't revive a creature that has died of old age, nor does it restore any missing body parts.",
    higherLevels: null,
    concentration: false,
    ritual: false
  },
  {
    name: "Slow",
    level: 3,
    school: "Transmutation",
    classes: ["Bard", "Sorcerer", "Wizard"],
    castingTime: "Action",
    range: "120 feet",
    components: "V, S, M (a drop of molasses)",
    duration: "Concentration, up to 1 minute",
    description: "You alter time around up to six creatures of your choice in a 40-foot Cube within range. Each target must succeed on a Wisdom saving throw or be affected by this spell for the duration.\n\nAn affected target's Speed is halved, it takes a −2 penalty to AC and Dexterity saving throws, and it can't take Reactions. On its turns, it can take either an action or a Bonus Action, not both, and it can make only one attack if it takes the Attack action. If it tries to cast a spell with a casting time of an action, roll 1d20; on an 11+, the spell takes effect on the target's next turn instead, and the target must use its action on that turn to complete the spell. Otherwise, the spell is wasted.\n\nAn affected creature repeats the save at the end of each of its turns, ending the spell on itself on a success.",
    higherLevels: null,
    concentration: true,
    ritual: false
  },
  {
    name: "Spirit Guardians",
    level: 3,
    school: "Conjuration",
    classes: ["Cleric"],
    castingTime: "Action",
    range: "Self (15-foot emanation)",
    components: "V, S, M (a prayer scroll)",
    duration: "Concentration, up to 10 minutes",
    description: "Protective spirits flit around you in a 15-foot Emanation for the duration. If you are good or neutral, their spectral form appears angelic or fey (your choice). If you are evil, they appear fiendish.\n\nWhen you cast this spell, you can designate creatures to be unaffected by it. Any other creature's Speed is halved in the Emanation, and whenever the Emanation enters a creature's space and whenever a creature enters the Emanation or ends its turn there, the creature must make a Wisdom saving throw. On a failed save, the creature takes 3d8 Radiant damage (if you are good or neutral) or 3d8 Necrotic damage (if you are evil). On a successful save, the creature takes half as much damage. A creature makes this save only once per turn.",
    higherLevels: "The damage increases by 1d8 for each slot level above 3.",
    concentration: true,
    ritual: false
  },
  {
    name: "Tongues",
    level: 3,
    school: "Divination",
    classes: ["Bard", "Cleric", "Sorcerer", "Warlock", "Wizard"],
    castingTime: "Action",
    range: "Touch",
    components: "V, M (a miniature ziggurat)",
    duration: "1 hour",
    description: "This spell grants the creature you touch the ability to understand any spoken or signed language that it hears or sees. Moreover, when the target communicates, any creature that knows at least one language can understand it if that creature can hear the target's speech or see the target's signing.",
    higherLevels: null,
    concentration: false,
    ritual: false
  },
  {
    name: "Vampiric Touch",
    level: 3,
    school: "Necromancy",
    classes: ["Sorcerer", "Warlock", "Wizard"],
    castingTime: "Action",
    range: "Self",
    components: "V, S",
    duration: "Concentration, up to 1 minute",
    description: "The touch of your shadow-wreathed hand can siphon life force from others to heal your wounds. Make a melee spell attack against one creature within reach. On a hit, the target takes 3d6 Necrotic damage, and you regain Hit Points equal to half the amount of Necrotic damage dealt.\n\nUntil the spell ends, you can make the attack again on each of your turns as a Magic action, targeting the same creature or a different one.",
    higherLevels: "The damage increases by 1d6 for each slot level above 3.",
    concentration: true,
    ritual: false
  },
];

// Sort spells by level then name
spells.sort((a, b) => {
  if (a.level !== b.level) return a.level - b.level;
  return a.name.localeCompare(b.name);
});