// D&D 5e (2024) Class and Subclass Reference Data

export const CLASS_DATA = [
  {
    id: 'barbarian',
    name: 'Barbarian',
    hitDie: 'd12',
    primaryAbility: 'Strength',
    savingThrows: ['Strength', 'Constitution'],
    armorProf: 'Light, Medium, Shields',
    weaponProf: 'Simple, Martial',
    color: '#C0392B',
    emoji: '🪓',
    tagline: 'A fierce warrior who channels primal rage',
    description: 'Barbarians are defined by their rage — a fierce, animalistic fury that drives them to feats of extraordinary strength and resilience. Whether drawing power from a totem spirit, an ancestral guardian, or the storm itself, barbarians are front-line combatants who thrive in the chaos of melee.',
    keyFeatures: [
      { level: 1, name: 'Rage', desc: 'Enter a fury that grants bonus melee damage, resistance to physical damage, and advantage on STR checks/saves. Limited uses per long rest.' },
      { level: 1, name: 'Unarmored Defense', desc: 'While not wearing armor, AC equals 10 + DEX mod + CON mod.' },
      { level: 2, name: 'Danger Sense', desc: 'Advantage on DEX saving throws against effects you can see (traps, spells, etc.).' },
      { level: 2, name: 'Reckless Attack', desc: 'Attack with advantage on STR-based melee attacks, but attacks against you also have advantage until your next turn.' },
      { level: 3, name: 'Primal Knowledge', desc: 'Gain proficiency in one skill from the Barbarian list.' },
      { level: 5, name: 'Extra Attack', desc: 'Attack twice when you take the Attack action.' },
      { level: 5, name: 'Fast Movement', desc: '+10 ft speed when not wearing heavy armor.' },
      { level: 7, name: 'Feral Instinct', desc: 'Advantage on initiative. Can act normally on first turn even if surprised (if you rage).' },
      { level: 9, name: 'Brutal Strike', desc: 'When using Reckless Attack, you can forgo advantage to deal extra damage and gain a special effect.' },
      { level: 11, name: 'Relentless Rage', desc: 'If you drop to 0 HP while raging, DC 10 CON save to drop to 1 HP instead. DC increases by 5 each time.' },
      { level: 15, name: 'Persistent Rage', desc: 'Rage only ends early if you fall unconscious or choose to end it.' },
      { level: 18, name: 'Indomitable Might', desc: 'STR checks can use your STR score as the minimum result.' },
      { level: 20, name: 'Primal Champion', desc: '+4 to STR and CON, maximums increase to 24.' },
    ],
    subclasses: [
      {
        name: 'Path of the Berserker',
        tagline: 'Channel Rage into Violent Fury',
        description: 'Barbarians who walk the Path of the Berserker direct their Rage primarily toward violence. Their path is one of untrammeled fury, and they thrill in the chaos of battle.',
        features: [
          { level: 3, name: 'Frenzy', desc: 'When using Reckless Attack while raging, deal extra damage (Rage Damage Bonus d6s) to the first target hit with a STR-based attack.' },
          { level: 6, name: 'Mindless Rage', desc: 'Immune to Charmed and Frightened while raging. Entering rage ends these conditions.' },
          { level: 10, name: 'Retaliation', desc: 'When you take damage from a creature within 5 ft, use your Reaction to make a melee attack against it.' },
          { level: 14, name: 'Intimidating Presence', desc: 'As a Bonus Action while raging, frighten a creature within 30 ft (WIS save vs 8 + prof + STR mod).' },
        ],
      },
      {
        name: 'Path of the Wild Heart',
        tagline: 'Walk with the Spirits of Nature',
        description: 'The Path of the Wild Heart is a spiritual journey, as the barbarian accepts a spirit animal as guide, protector, and inspiration.',
        features: [
          { level: 3, name: 'Animal Speaker', desc: 'You can cast Beast Sense and Speak with Animals as rituals.' },
          { level: 3, name: 'Rage of the Wilds', desc: 'When you rage, choose Bear (resistance to all damage except Psychic), Eagle (Dash as Bonus Action, opportunity attacks against you have disadvantage), or Wolf (allies have advantage on attacks against creatures within 5 ft of you).' },
          { level: 6, name: 'Aspect of the Wilds', desc: 'Choose Owl (darkvision 60 ft, advantage on Perception), Panther (climb/swim speed equal to walking), or Salmon (swim speed equal to walking, breathe underwater).' },
          { level: 10, name: 'Nature Speaker', desc: 'You can cast Commune with Nature as a ritual.' },
          { level: 14, name: 'Power of the Wilds', desc: 'Choose Falcon (fly speed while raging), Lion (knock prone when hitting with Reckless Attack), or Ram (push creatures 15 ft when hitting with Reckless Attack).' },
        ],
      },
      {
        name: 'Path of the World Tree',
        tagline: 'Draw Power from the Cosmic World Tree',
        description: 'Barbarians who follow the Path of the World Tree connect to the cosmic tree that links all planes of existence, gaining the ability to travel between worlds and channel its vitality.',
        features: [
          { level: 3, name: 'Vitality of the Tree', desc: 'When you rage, you and allies within 10 ft gain temporary HP equal to your Barbarian level.' },
          { level: 6, name: 'Branches of the Tree', desc: 'When a creature you can see within 30 ft is hit by an attack while you rage, use your Reaction to teleport it up to 30 ft to an unoccupied space you can see.' },
          { level: 10, name: 'Battering Roots', desc: 'While raging, the ground within 15 ft is difficult terrain for enemies.' },
          { level: 14, name: 'Travel Along the Tree', desc: 'While raging, as a Bonus Action, teleport up to 60 ft. Can bring one willing creature within 10 ft.' },
        ],
      },
      {
        name: 'Path of the Zealot',
        tagline: 'Fight with Divine Fury',
        description: 'Some deities inspire their followers to pitch themselves into a ferocious battle fury. These barbarians are zealots — warriors who channel their rage into powerful displays of divine power.',
        features: [
          { level: 3, name: 'Divine Fury', desc: 'While raging, the first creature you hit each turn takes extra Necrotic or Radiant damage equal to 1d6 + half your Barbarian level.' },
          { level: 3, name: 'Warrior of the Gods', desc: 'Spells that restore you to life (not Revivify) dont require material components.' },
          { level: 6, name: 'Fanatical Focus', desc: 'Once per rage, reroll a failed saving throw.' },
          { level: 10, name: 'Zealous Presence', desc: 'As a Bonus Action, up to 10 allies within 60 ft gain advantage on attack rolls and saving throws until start of your next turn. Once per long rest.' },
          { level: 14, name: 'Rage Beyond Death', desc: 'While raging, dropping to 0 HP doesnt knock you unconscious. You still make death saves. You only die if you fail all three or rage ends while at 0.' },
        ],
      },
    ],
  },
  {
    id: 'bard',
    name: 'Bard',
    hitDie: 'd8',
    primaryAbility: 'Charisma',
    savingThrows: ['Dexterity', 'Charisma'],
    armorProf: 'Light',
    weaponProf: 'Simple',
    color: '#8E44AD',
    emoji: '🎵',
    tagline: 'An inspiring magician whose music echoes with creation',
    description: 'Whether scholar, skald, or scoundrel, bards weave magic through words and music. Their spellcasting draws on bardic lore — a vast collection of knowledge spanning every subject. Bards are versatile support characters who inspire allies, debilitate enemies, and fill skill gaps.',
    keyFeatures: [
      { level: 1, name: 'Bardic Inspiration', desc: 'Bonus Action to give a creature within 60 ft an Inspiration die (starts as d6, scales). They can add it to one ability check, attack roll, or saving throw within 10 minutes.' },
      { level: 1, name: 'Spellcasting', desc: 'Full caster using CHA. Known spells from the Bard list. Ritual casting available.' },
      { level: 2, name: 'Expertise', desc: 'Double proficiency bonus for two skills.' },
      { level: 2, name: 'Jack of All Trades', desc: 'Add half proficiency bonus to ability checks you arent proficient in.' },
      { level: 5, name: 'Font of Inspiration', desc: 'Bardic Inspiration recharges on a Short Rest.' },
      { level: 10, name: 'Magical Secrets', desc: 'Learn two spells from any spell list.' },
      { level: 18, name: 'Superior Inspiration', desc: 'If you have no Bardic Inspiration uses when you roll initiative, regain one use.' },
      { level: 20, name: 'Words of Creation', desc: 'Once per long rest, use Bardic Inspiration without expending a use. Your Bardic Inspiration die becomes a d12.' },
    ],
    subclasses: [
      {
        name: 'College of Dance',
        tagline: 'Move with Supernatural Grace',
        description: 'Bards of the College of Dance know that words and music arent the only way to create art. These bards use graceful movement and expertly choreographed steps to channel their magic.',
        features: [
          { level: 3, name: 'Dazzling Footwork', desc: 'While not wearing armor or shield, AC equals 10 + DEX mod + CHA mod. Your speed increases by 10 ft. No opportunity attacks against you when you move.' },
          { level: 3, name: 'Inspiring Movement', desc: 'When a creature uses your Bardic Inspiration, it can also use its Reaction to move up to half its speed without provoking opportunity attacks.' },
          { level: 6, name: 'Tandem Footwork', desc: 'When you roll initiative, choose up to a number of creatures equal to CHA mod within 30 ft. They each roll a d4 and add it to their initiative.' },
          { level: 14, name: 'Leading Evasion', desc: 'When you succeed on a DEX save, you and allies within 5 ft take no damage (half on a failure instead of full).' },
        ],
      },
      {
        name: 'College of Glamour',
        tagline: 'Weave Fey Magic Through Performance',
        description: 'The College of Glamour is home to bards who mastered their craft in the Feywild or under the tutelage of fey creatures. These bards command attention and can reshape minds.',
        features: [
          { level: 3, name: 'Mantle of Inspiration', desc: 'Bonus Action to give temp HP to allies within 60 ft and they can move without provoking opportunity attacks.' },
          { level: 3, name: 'Enthralling Performance', desc: 'After performing for 1 minute, charm humanoids within 60 ft (WIS save).' },
          { level: 6, name: 'Mantle of Majesty', desc: 'Cast Command as a Bonus Action without expending a spell slot while concentrating on this ability for 1 minute.' },
          { level: 14, name: 'Unbreakable Majesty', desc: 'Creatures attacking you must make a CHA save or their attack automatically misses. They must choose a new target or waste the attack.' },
        ],
      },
      {
        name: 'College of Lore',
        tagline: 'Collect Knowledge from Any Source',
        description: 'Bards of the College of Lore know something about most things, collecting bits of knowledge from sources as diverse as scholarly tomes and peasant tales.',
        features: [
          { level: 3, name: 'Bonus Proficiencies', desc: 'Gain proficiency in three skills of your choice.' },
          { level: 3, name: 'Cutting Words', desc: 'When a creature within 60 ft makes an attack roll, ability check, or damage roll, use Reaction to subtract your Bardic Inspiration die from the roll.' },
          { level: 6, name: 'Additional Magical Secrets', desc: 'Learn two spells from any spell list. They count as Bard spells for you.' },
          { level: 14, name: 'Peerless Skill', desc: 'When you make an ability check and fail, expend a Bardic Inspiration die and add it to the roll, potentially turning a failure into a success.' },
        ],
      },
      {
        name: 'College of Valor',
        tagline: 'Inspire Heroism in Battle',
        description: 'Bards of the College of Valor are daring skalds whose tales keep alive the memory of great heroes of the past, inspiring a new generation to greatness.',
        features: [
          { level: 3, name: 'Combat Inspiration', desc: 'Creatures using your Bardic Inspiration can also add the die to damage or AC (as a Reaction).' },
          { level: 3, name: 'Martial Training', desc: 'Proficiency with medium armor, shields, and martial weapons.' },
          { level: 6, name: 'Extra Attack', desc: 'Attack twice when you take the Attack action.' },
          { level: 14, name: 'Battle Magic', desc: 'When you cast a Bard spell with a casting time of an Action, you can make one weapon attack as a Bonus Action.' },
        ],
      },
    ],
  },
  {
    id: 'cleric',
    name: 'Cleric',
    hitDie: 'd8',
    primaryAbility: 'Wisdom',
    savingThrows: ['Wisdom', 'Charisma'],
    armorProf: 'Light, Medium, Shields',
    weaponProf: 'Simple',
    color: '#F1C40F',
    emoji: '✝️',
    tagline: 'A divine champion who wields the power of the gods',
    description: 'Clerics are intermediaries between the mortal world and the distant planes of the gods. As varied as the gods they serve, clerics strive to embody the handiwork of their deities. A cleric is imbued with divine magic that can heal, protect, and destroy.',
    keyFeatures: [
      { level: 1, name: 'Spellcasting', desc: 'Full caster using WIS. Prepare spells daily from the full Cleric list. Ritual casting available.' },
      { level: 1, name: 'Channel Divinity', desc: 'Channel divine energy for magical effects. All clerics get Turn Undead. Subclass grants additional options.' },
      { level: 2, name: 'Holy Order', desc: 'Choose Protector (martial weapons and heavy armor), Scholar (one skill and one cantrip from any list), or Thaumaturge (+WIS to cantrip damage).' },
      { level: 5, name: 'Sear Undead', desc: 'When you use Turn Undead, undead that fail take radiant damage.' },
      { level: 7, name: 'Blessed Strikes', desc: 'Deal extra radiant or necrotic damage once per turn with weapon attacks or cantrips.' },
      { level: 10, name: 'Divine Intervention', desc: 'Call on your deity. Roll percentile dice; if you roll equal to or under your Cleric level, your deity intervenes.' },
      { level: 20, name: 'Greater Divine Intervention', desc: 'Divine Intervention succeeds automatically once per long rest. Choose from a list of powerful effects.' },
    ],
    subclasses: [
      {
        name: 'Life Domain',
        tagline: 'Master of Healing Magic',
        description: 'The Life domain focuses on the vibrant positive energy that sustains all life. Gods of life promote vitality and health through healing the sick and wounded.',
        features: [
          { level: 3, name: 'Disciple of Life', desc: 'Healing spells are more effective — add 2 + spell level to the HP restored by any healing spell you cast.' },
          { level: 3, name: 'Preserve Life (Channel Divinity)', desc: 'As an Action, distribute HP (5x Cleric level) among creatures within 30 ft, restoring up to half their max HP.' },
          { level: 6, name: 'Blessed Healer', desc: 'When you cast a healing spell on another, you regain HP equal to 2 + spell level.' },
          { level: 14, name: 'Supreme Healing', desc: 'Instead of rolling dice for healing spells, use the maximum number on each die.' },
        ],
      },
      {
        name: 'Light Domain',
        tagline: 'Wield the Power of Radiant Light',
        description: 'Gods of light promote ideals of rebirth and renewal, truth, vigilance, and beauty. Clerics of a god of light are enlightened souls infused with radiance.',
        features: [
          { level: 3, name: 'Radiance of the Dawn (Channel Divinity)', desc: 'As an Action, dispel magical darkness within 30 ft and deal radiant damage to hostile creatures (CON save for half).' },
          { level: 3, name: 'Warding Flare', desc: 'Reaction when attacked: impose disadvantage on the attack roll. Uses equal to WIS mod per long rest.' },
          { level: 6, name: 'Improved Warding Flare', desc: 'Can use Warding Flare to protect creatures other than yourself within 30 ft.' },
          { level: 14, name: 'Corona of Light', desc: 'As an Action, emit bright light 60 ft. Enemies in the light have disadvantage on saves against fire and radiant spells.' },
        ],
      },
      {
        name: 'Trickery Domain',
        tagline: 'Deceive and Outmaneuver',
        description: 'Gods of trickery are mischief-makers and instigators who represent the values of rebellion, liberation, and free will. Their clerics prefer subtlety over direct confrontation.',
        features: [
          { level: 3, name: 'Blessing of the Trickster', desc: 'Give a creature advantage on Stealth checks for 1 hour.' },
          { level: 3, name: 'Invoke Duplicity (Channel Divinity)', desc: 'Create an illusory duplicate of yourself within 30 ft for 1 minute. Cast spells as if in its space. Advantage on attacks when you and duplicate are within 5 ft of target.' },
          { level: 6, name: 'Tricksters Transposition', desc: 'Teleport to swap places with your duplicate.' },
          { level: 14, name: 'Improved Duplicity', desc: 'You and allies within 30 ft of your duplicate are invisible to creatures farther than 5 ft away for a number of rounds equal to your WIS mod.' },
        ],
      },
      {
        name: 'War Domain',
        tagline: 'Blessed by the Gods of War',
        description: 'War has many manifestations. Gods of war watch over warriors and reward them for their great deeds. Their clerics excel at inspiring others to fight.',
        features: [
          { level: 3, name: 'War Priest', desc: 'When you take the Attack action, make one extra weapon attack as a Bonus Action. Uses equal to WIS mod per long rest.' },
          { level: 3, name: 'Guided Strike (Channel Divinity)', desc: '+10 bonus to an attack roll you or a creature within 30 ft makes.' },
          { level: 6, name: 'War Gods Blessing', desc: 'When a creature within 30 ft makes an attack roll, use your Reaction to grant +10 to the roll (Channel Divinity).' },
          { level: 14, name: 'Avatar of Battle', desc: 'Resistance to Bludgeoning, Piercing, and Slashing damage.' },
        ],
      },
    ],
  },
  {
    id: 'druid',
    name: 'Druid',
    hitDie: 'd8',
    primaryAbility: 'Wisdom',
    savingThrows: ['Intelligence', 'Wisdom'],
    armorProf: 'Light, Shields',
    weaponProf: 'Simple',
    color: '#27AE60',
    emoji: '🌿',
    tagline: 'A wielder of nature magic and shapeshifting',
    description: 'Druids revere nature above all, gaining their spells and other magical powers either from the force of nature itself or from a nature deity. Druids are masters of shapeshifting, terrain manipulation, and summoning the forces of the natural world.',
    keyFeatures: [
      { level: 1, name: 'Spellcasting', desc: 'Full caster using WIS. Prepare spells daily from the Druid list. Ritual casting available.' },
      { level: 1, name: 'Druidic', desc: 'You know Druidic, the secret language of druids.' },
      { level: 2, name: 'Wild Shape', desc: 'Transform into a beast you have seen. Lasts for a number of hours equal to half your Druid level. Can use twice per short rest.' },
      { level: 2, name: 'Wild Companion', desc: 'Expend a Wild Shape use to cast Find Familiar without material components.' },
      { level: 5, name: 'Wild Resurgence', desc: 'Once per long rest, regain a Wild Shape use or expend a Wild Shape use to regain a spell slot.' },
      { level: 15, name: 'Improved Wild Shape', desc: 'Can Wild Shape as a Bonus Action. Stay in Wild Shape for up to 8 hours.' },
      { level: 18, name: 'Beast Spells', desc: 'Cast spells while in Wild Shape form.' },
      { level: 20, name: 'Archdruid', desc: 'Unlimited Wild Shape uses.' },
    ],
    subclasses: [
      {
        name: 'Circle of the Land',
        tagline: 'Draw Power from Specific Terrain',
        description: 'Druids of the Circle of the Land are mystics and sages who safeguard ancient knowledge and rites through an oral tradition. These druids gain additional spells based on the type of terrain that shaped their druidic path.',
        features: [
          { level: 3, name: 'Circle Spells', desc: 'Gain bonus spells based on your chosen land type (Arid, Polar, Temperate, or Tropical). These are always prepared.' },
          { level: 3, name: 'Land Recovery', desc: 'Once per long rest, recover spell slot levels totaling half your Druid level (rounded up) during a short rest.' },
          { level: 6, name: 'Natures Ward', desc: 'Immune to being Poisoned. Resistance to Poison damage. Immune to disease.' },
          { level: 10, name: 'Natures Sanctuary', desc: 'Beasts and Plant creatures must make a WIS save to attack you. On a failure, they must choose a different target.' },
          { level: 14, name: 'Natures Stride', desc: 'Moving through difficult terrain costs no extra movement. You can pass through plants without being slowed or taking damage.' },
        ],
      },
      {
        name: 'Circle of the Moon',
        tagline: 'Master of Beast Forms',
        description: 'Druids of the Circle of the Moon are fierce guardians of the wilds, who transform into powerful beast forms to protect the natural world.',
        features: [
          { level: 3, name: 'Combat Wild Shape', desc: 'Wild Shape as a Bonus Action. Expend spell slots while in beast form to heal yourself (1d8 per slot level).' },
          { level: 3, name: 'Circle Forms', desc: 'Can transform into beasts with CR up to your Druid level divided by 3 (rounded down). At 3rd level, CR 1.' },
          { level: 6, name: 'Improved Circle Forms', desc: 'While in Wild Shape, your attacks count as magical.' },
          { level: 10, name: 'Moonlight Step', desc: 'Once per turn while in Wild Shape, teleport up to 30 ft to an unoccupied space you can see and gain advantage on next attack.' },
          { level: 14, name: 'Thousand Forms', desc: 'Cast Alter Self at will without expending a spell slot.' },
        ],
      },
      {
        name: 'Circle of the Sea',
        tagline: 'Command the Power of Oceans and Storms',
        description: 'Druids of the Circle of the Sea draw on the power of coastal and underwater environments, wielding the fury of crashing waves and howling winds.',
        features: [
          { level: 3, name: 'Wrath of the Sea', desc: 'As a Bonus Action while Wild Shape is active, lash out at a creature within 30 ft with water. DEX save or take cold damage and be pushed 15 ft.' },
          { level: 6, name: 'Aquatic Affinity', desc: 'Gain a swim speed equal to your walking speed and can breathe underwater.' },
          { level: 10, name: 'Stormborn', desc: 'Resistance to Cold and Lightning damage. When you deal cold or lightning damage, push the target 15 ft.' },
          { level: 14, name: 'Oceanic Gift', desc: 'Once per turn when you deal cold or lightning damage, you or an ally within 30 ft gains temporary HP equal to your WIS mod + your Druid level.' },
        ],
      },
      {
        name: 'Circle of the Stars',
        tagline: 'Read the Stars and Channel Constellations',
        description: 'Druids of the Circle of Stars have tracked heavenly patterns since time immemorial, discovering secrets hidden amid the constellations. These druids channel starlight to augment their magic.',
        features: [
          { level: 3, name: 'Star Map', desc: 'Gain Guidance cantrip and can cast Guiding Bolt without a spell slot a number of times equal to your proficiency bonus.' },
          { level: 3, name: 'Starry Form', desc: 'Expend a Wild Shape to assume a starry form. Choose Archer (bonus radiant attack), Chalice (heal when casting spells), or Dragon (minimum 10 on concentration saves, fly).' },
          { level: 6, name: 'Cosmic Omen', desc: 'After a long rest, roll a die. Even = Weal (add a d6 to ally rolls as Reaction). Odd = Woe (subtract a d6 from enemy rolls as Reaction). Prof bonus uses per long rest.' },
          { level: 10, name: 'Twinkling Constellations', desc: 'Change your Starry Form constellation at the start of each turn. The Archer and Chalice effects improve.' },
          { level: 14, name: 'Full of Stars', desc: 'While in Starry Form, resistance to Bludgeoning, Piercing, and Slashing damage.' },
        ],
      },
    ],
  },
  {
    id: 'fighter',
    name: 'Fighter',
    hitDie: 'd10',
    primaryAbility: 'Strength or Dexterity',
    savingThrows: ['Strength', 'Constitution'],
    armorProf: 'All armor, Shields',
    weaponProf: 'Simple, Martial',
    color: '#E67E22',
    emoji: '⚔️',
    tagline: 'A master of martial combat and tactical warfare',
    description: 'Fighters are the most versatile combatants on the battlefield. Trained in the use of every weapon and armor, fighters have an unmatched mastery of combat techniques. Whether wielding sword and shield, a massive greatsword, or a bow, the fighter excels.',
    keyFeatures: [
      { level: 1, name: 'Fighting Style', desc: 'Choose a fighting style: Archery, Defense, Dueling, Great Weapon Fighting, Protection, or Two-Weapon Fighting.' },
      { level: 1, name: 'Second Wind', desc: 'Bonus Action to regain HP equal to 1d10 + Fighter level. Once per short rest.' },
      { level: 2, name: 'Action Surge', desc: 'Take one additional Action on your turn. Once per short rest (twice at 17th level).' },
      { level: 5, name: 'Extra Attack', desc: 'Attack twice when you take the Attack action. Increases to 3 at 11th and 4 at 20th.' },
      { level: 9, name: 'Indomitable', desc: 'Reroll a failed saving throw. Uses increase at higher levels.' },
      { level: 9, name: 'Tactical Mind', desc: 'Add 1d10 to a failed ability check. If it still fails, the use isnt expended.' },
      { level: 13, name: 'Studied Attacks', desc: 'When you miss an attack, you have advantage on your next attack against that creature before end of your next turn.' },
    ],
    subclasses: [
      {
        name: 'Battle Master',
        tagline: 'Master of Tactical Maneuvers',
        description: 'Battle Masters employ martial techniques passed down through generations. They use superiority dice to fuel special maneuvers that give them an edge in combat.',
        features: [
          { level: 3, name: 'Combat Superiority', desc: 'Learn 3 maneuvers. Gain 4 superiority dice (d8, scales to d12). Regain on short rest.' },
          { level: 3, name: 'Student of War', desc: 'Gain proficiency with one artisans tools.' },
          { level: 7, name: 'Know Your Enemy', desc: 'Study a creature for 1 minute to learn if its equal, superior, or inferior in two characteristics.' },
          { level: 10, name: 'Improved Combat Superiority', desc: 'Learn 2 more maneuvers. Superiority dice become d10.' },
          { level: 15, name: 'Relentless', desc: 'When you roll initiative with no superiority dice remaining, regain 1.' },
        ],
      },
      {
        name: 'Champion',
        tagline: 'Push Physical Prowess to Superhuman Limits',
        description: 'A Champion focuses on raw physical power, honed to deadly perfection. Simple but devastatingly effective.',
        features: [
          { level: 3, name: 'Improved Critical', desc: 'Critical hit on a 19 or 20.' },
          { level: 3, name: 'Remarkable Athlete', desc: 'Add half proficiency (rounded up) to STR, DEX, or CON checks that dont already use proficiency. Running long jump distance increases by STR mod feet.' },
          { level: 7, name: 'Additional Fighting Style', desc: 'Choose a second Fighting Style.' },
          { level: 10, name: 'Heroic Warrior', desc: 'When you have no uses of Second Wind, you can regain one by giving yourself the Heroic Inspiration die.' },
          { level: 15, name: 'Superior Critical', desc: 'Critical hit on an 18, 19, or 20.' },
          { level: 18, name: 'Survivor', desc: 'At the start of each turn, regain HP equal to 5 + CON mod if you have half or fewer HP remaining and at least 1 HP.' },
        ],
      },
      {
        name: 'Eldritch Knight',
        tagline: 'Blend Martial Prowess with Arcane Magic',
        description: 'The Eldritch Knight combines martial mastery with careful study of magic. They use spells to augment their combat abilities, primarily drawing from abjuration and evocation.',
        features: [
          { level: 3, name: 'Spellcasting', desc: 'Learn Wizard cantrips and spells (INT-based). Primarily from Abjuration and Evocation, with some flexibility.' },
          { level: 3, name: 'War Bond', desc: 'Bond with weapons. Cannot be disarmed. Summon bonded weapons to your hand as a Bonus Action.' },
          { level: 7, name: 'War Magic', desc: 'When you cast a cantrip, make one weapon attack as a Bonus Action.' },
          { level: 10, name: 'Eldritch Strike', desc: 'When you hit with a weapon, the target has disadvantage on its next save against your spells.' },
          { level: 15, name: 'Arcane Charge', desc: 'When you use Action Surge, teleport up to 30 ft to an unoccupied space.' },
          { level: 18, name: 'Improved War Magic', desc: 'When you cast a spell with an Action, make one weapon attack as a Bonus Action.' },
        ],
      },
      {
        name: 'Psi Warrior',
        tagline: 'Augment Combat with Psionic Power',
        description: 'Psi Warriors are fighters who augment their physical might with psi-infused weapon strikes, telekinetic lashes, and barriers of mental force.',
        features: [
          { level: 3, name: 'Psionic Power', desc: 'Gain Psionic Energy dice (d6, scales). Use for Protective Field (reduce damage to self or ally), Psionic Strike (extra force damage on hit), or Telekinetic Movement (move object or creature).' },
          { level: 7, name: 'Telekinetic Adept', desc: 'Psi-Powered Leap (fly speed for the turn) and Telekinetic Thrust (push creatures 10 ft or knock prone on Psionic Strike).' },
          { level: 10, name: 'Guarded Mind', desc: 'Resistance to Psychic damage. Expend Psionic Energy to end Charmed or Frightened.' },
          { level: 15, name: 'Bulwark of Force', desc: 'As a Bonus Action, create shields of force for up to INT mod creatures within 30 ft, granting half cover for 1 minute.' },
          { level: 18, name: 'Telekinetic Master', desc: 'Cast Telekinesis without components (concentration). When you do, make one weapon attack as a Bonus Action.' },
        ],
      },
    ],
  },
  {
    id: 'monk',
    name: 'Monk',
    hitDie: 'd8',
    primaryAbility: 'Dexterity & Wisdom',
    savingThrows: ['Strength', 'Dexterity'],
    armorProf: 'None',
    weaponProf: 'Simple, Martial (with Finesse or Light)',
    color: '#1ABC9C',
    emoji: '👊',
    tagline: 'A martial artist who harnesses the power of body and soul',
    description: 'Monks are united in their ability to magically harness the energy that flows in their bodies. Whether channeled as a striking display of combat prowess or a subtler focus of defensive ability and speed, this energy infuses all that a monk does.',
    keyFeatures: [
      { level: 1, name: 'Martial Arts', desc: 'Use DEX for monk weapons and unarmed strikes. Martial Arts die starts at d6, scales up. Bonus Action for extra unarmed strike.' },
      { level: 1, name: 'Unarmored Defense', desc: 'AC = 10 + DEX mod + WIS mod when wearing no armor.' },
      { level: 2, name: 'Focus Points', desc: 'Pool of points equal to Monk level. Fuel special abilities: Flurry of Blows, Patient Defense, Step of the Wind.' },
      { level: 2, name: 'Unarmored Movement', desc: 'Speed increases by 10 ft (scales to +30 ft at level 18). Eventually walk on walls and water.' },
      { level: 3, name: 'Deflect Attacks', desc: 'Use Reaction to reduce incoming damage. If reduced to 0, deflect the attack entirely.' },
      { level: 5, name: 'Extra Attack', desc: 'Attack twice when you take the Attack action.' },
      { level: 5, name: 'Stunning Strike', desc: 'When you hit, spend 1 Focus Point. Target must make CON save or be Stunned.' },
      { level: 10, name: 'Self-Restoration', desc: 'End one Charmed, Frightened, or Poisoned condition at the start of your turn.' },
      { level: 13, name: 'Deflect Energy', desc: 'Deflect Attacks works against ranged spell attacks.' },
      { level: 14, name: 'Disciplined Survivor', desc: 'Proficiency in all saving throws. Spend Focus Points to reroll failed saves.' },
      { level: 18, name: 'Superior Defense', desc: 'At start of turn while Focus Points remain, gain resistance to all but Force damage.' },
      { level: 20, name: 'Body and Mind', desc: '+4 to DEX and WIS, maximums increase to 24.' },
    ],
    subclasses: [
      {
        name: 'Warrior of Mercy',
        tagline: 'Deal Death and Grant Mercy',
        description: 'Monks of the Way of Mercy learn to manipulate the life force of others to bring aid or suffering. They are wandering healers who can also become harbingers of death.',
        features: [
          { level: 3, name: 'Hand of Healing', desc: 'Spend 1 Focus Point to restore HP equal to Martial Arts die + WIS mod when you use Flurry of Blows.' },
          { level: 3, name: 'Hand of Harm', desc: 'Spend 1 Focus Point to deal extra Necrotic damage equal to Martial Arts die + WIS mod when you hit with Flurry of Blows. Can also poison the target.' },
          { level: 6, name: 'Physicians Touch', desc: 'Hand of Healing also ends one disease, Blinded, Deafened, Paralyzed, Poisoned, or Stunned condition.' },
          { level: 11, name: 'Flurry of Healing and Harm', desc: 'Can use Hand of Healing and Hand of Harm without spending Focus Points when you use Flurry of Blows.' },
          { level: 17, name: 'Hand of Ultimate Mercy', desc: 'Spend 5 Focus Points to cast Raise Dead without material components.' },
        ],
      },
      {
        name: 'Warrior of Shadow',
        tagline: 'Strike from the Darkness',
        description: 'Monks of the Way of Shadow follow a tradition that values stealth and subterfuge. These monks serve as spies, assassins, and infiltrators.',
        features: [
          { level: 3, name: 'Shadow Arts', desc: 'Spend 1 Focus Point to cast Darkness, Darkvision, Pass without Trace, or Silence.' },
          { level: 6, name: 'Shadow Step', desc: 'When in dim light or darkness, teleport up to 60 ft to another dim/dark space as a Bonus Action. Advantage on next melee attack.' },
          { level: 11, name: 'Improved Shadow Step', desc: 'When you use Shadow Step, one creature within 5 ft of your origin is blinded until end of your next turn (CON save).' },
          { level: 17, name: 'Cloak of Shadows', desc: 'While in dim light or darkness, become Invisible as a Bonus Action until you attack, cast a spell, or enter bright light.' },
        ],
      },
      {
        name: 'Warrior of the Elements',
        tagline: 'Wield the Four Elements',
        description: 'Monks of the Way of the Four Elements channel the raw power of the elements through their Focus, bending fire, water, earth, and air to their will.',
        features: [
          { level: 3, name: 'Elemental Attunement', desc: 'Learn Elementalism cantrip. When you use Flurry of Blows, replace one unarmed strike with elemental burst (15 ft cone or 30 ft line, DEX save, your choice of Acid, Cold, Fire, Lightning, or Thunder damage).' },
          { level: 6, name: 'Environmental Burst', desc: 'Elemental burst increases to 20 ft cone or 60 ft line. Gain swim speed and water breathing or climb speed, depending on choice.' },
          { level: 11, name: 'Stride of the Elements', desc: 'Gain a Fly speed equal to walking speed.' },
          { level: 17, name: 'Elemental Epitome', desc: 'When you use Step of the Wind, damage resistance and extra elemental damage on attacks for 1 minute.' },
        ],
      },
      {
        name: 'Warrior of the Open Hand',
        tagline: 'The Classic Martial Artist',
        description: 'Monks of the Way of the Open Hand are the ultimate masters of martial arts combat. They learn techniques to push and trip opponents, manipulate ki to heal, and practice meditation to protect themselves.',
        features: [
          { level: 3, name: 'Open Hand Technique', desc: 'When you hit with Flurry of Blows, impose one effect: knock Prone (DEX save), push 15 ft (STR save), or prevent Reactions until end of your next turn.' },
          { level: 6, name: 'Wholeness of Body', desc: 'As a Bonus Action, regain HP equal to your Martial Arts die x3. Once per long rest, or spend 2 Focus Points.' },
          { level: 11, name: 'Fleet Step', desc: 'When you take a Bonus Action, you can also use Step of the Wind without spending a Focus Point.' },
          { level: 17, name: 'Quivering Palm', desc: 'After hitting a creature, set up vibrations that last for a number of days equal to your Monk level. Use Action to end them — the target must make a CON save or drop to 0 HP.' },
        ],
      },
    ],
  },
  {
    id: 'paladin',
    name: 'Paladin',
    hitDie: 'd10',
    primaryAbility: 'Strength & Charisma',
    savingThrows: ['Wisdom', 'Charisma'],
    armorProf: 'All armor, Shields',
    weaponProf: 'Simple, Martial',
    color: '#D4AC0D',
    emoji: '🛡️',
    tagline: 'A holy warrior bound to a sacred oath',
    description: 'Whether sworn before a gods altar, in a sacred glade, or in a moment of desperation, the oath of a paladin is a powerful bond. It is a source of power that turns a devout warrior into a blessed champion.',
    keyFeatures: [
      { level: 1, name: 'Lay on Hands', desc: 'Pool of healing power equal to 5 x Paladin level. Restore HP, cure disease, or neutralize poison.' },
      { level: 1, name: 'Spellcasting', desc: 'Half caster using CHA. Prepare spells daily from the Paladin list.' },
      { level: 2, name: 'Fighting Style', desc: 'Choose a fighting style that complements your combat approach.' },
      { level: 2, name: 'Divine Smite', desc: 'When you hit, expend a spell slot to deal extra radiant damage (2d8 + 1d8 per slot level above 1st, max 5d8). +1d8 vs undead/fiends.' },
      { level: 3, name: 'Channel Divinity', desc: 'Channel your oath for magical effects. Options vary by subclass.' },
      { level: 5, name: 'Extra Attack', desc: 'Attack twice when you take the Attack action.' },
      { level: 5, name: 'Faithful Steed', desc: 'Always have Find Steed prepared; it doesnt count against prepared spells.' },
      { level: 6, name: 'Aura of Protection', desc: 'You and allies within 10 ft add your CHA mod to all saving throws (30 ft at 18th level).' },
      { level: 9, name: 'Abjure Foes', desc: 'As an Action, frighten enemies within 60 ft (WIS save). Frightened targets speed is 0.' },
      { level: 14, name: 'Restoring Touch', desc: 'Use Lay on Hands to remove conditions: Blinded, Charmed, Deafened, Frightened, Paralyzed, or Stunned.' },
    ],
    subclasses: [
      {
        name: 'Oath of Devotion',
        tagline: 'The Archetypal Holy Knight',
        description: 'The Oath of Devotion binds a paladin to the loftiest ideals of justice, virtue, and order. Called holy knights or white knights, these paladins meet the ideal of the knight in shining armor.',
        features: [
          { level: 3, name: 'Sacred Weapon (Channel Divinity)', desc: 'As a Bonus Action, imbue weapon with positive energy. Add CHA mod to attack rolls for 10 minutes. Weapon emits bright light.' },
          { level: 7, name: 'Aura of Devotion', desc: 'You and allies within 10 ft cant be Charmed (30 ft at 18th level).' },
          { level: 15, name: 'Smite of Protection', desc: 'When you use Divine Smite, choose allies within 30 ft equal to CHA mod. Each gains temp HP equal to 1d8 + spell slot level used.' },
          { level: 20, name: 'Holy Nimbus', desc: 'Emit bright light 30 ft for 10 minutes. Enemies starting turn in it take radiant damage. Advantage on saves vs fiend/undead spells.' },
        ],
      },
      {
        name: 'Oath of Glory',
        tagline: 'Race to Live Up to a Heroic Destiny',
        description: 'Paladins who take the Oath of Glory believe they and their companions are destined to achieve glory through deeds of heroism. They train diligently and push their bodies to prepare for that destiny.',
        features: [
          { level: 3, name: 'Peerless Athlete (Channel Divinity)', desc: 'Bonus Action: for 1 hour, advantage on Athletics and Acrobatics, carry/push/lift double, jump distance increases by 10 ft.' },
          { level: 3, name: 'Inspiring Smite (Channel Divinity)', desc: 'After using Divine Smite, distribute temp HP among creatures within 30 ft (2d8 + spell slot level).' },
          { level: 7, name: 'Aura of Alacrity', desc: 'Your walking speed increases by 10 ft. Allies within 10 ft gain +10 ft speed (30 ft at 18th).' },
          { level: 15, name: 'Glorious Defense', desc: 'When a creature within 10 ft is hit, use Reaction to add CHA mod to its AC. If this causes a miss, you can make one attack against the attacker.' },
          { level: 20, name: 'Living Legend', desc: 'For 10 minutes: advantage on CHA checks, once per turn turn a miss into a hit, reroll a failed save (once).' },
        ],
      },
      {
        name: 'Oath of the Ancients',
        tagline: 'Protect the Light Against Darkness',
        description: 'The Oath of the Ancients is as old as the race of elves and the rituals of the druids. Paladins who swear this oath ally themselves with the forces of light in the cosmic struggle against darkness.',
        features: [
          { level: 3, name: 'Natures Wrath (Channel Divinity)', desc: 'Cause spectral vines to restrain a creature you can see within 15 ft (STR or DEX save).' },
          { level: 7, name: 'Aura of Warding', desc: 'You and allies within 10 ft have resistance to damage from spells (30 ft at 18th level).' },
          { level: 15, name: 'Undying Sentinel', desc: 'When reduced to 0 HP and not killed outright, drop to 1 HP instead. Once per long rest. Also, you suffer no penalties of old age.' },
          { level: 20, name: 'Elder Champion', desc: 'Transform for 10 minutes: regain 10 HP each turn, cast Paladin spells as Bonus Action, enemies within 10 ft have disadvantage on saves vs your spells.' },
        ],
      },
      {
        name: 'Oath of Vengeance',
        tagline: 'Punish Those Who Commit Grievous Sins',
        description: 'The Oath of Vengeance is a solemn commitment to punish those who have committed a grievous sin. These paladins are willing to sacrifice their own righteousness to mete out justice.',
        features: [
          { level: 3, name: 'Vow of Enmity (Channel Divinity)', desc: 'Bonus Action: choose a creature within 30 ft. Advantage on attack rolls against it for 1 minute.' },
          { level: 7, name: 'Relentless Avenger', desc: 'When you hit with an opportunity attack, can move up to half your speed without provoking. Move toward the target.' },
          { level: 15, name: 'Soul of Vengeance', desc: 'When the target of your Vow of Enmity makes an attack, you can make a melee attack against it as a Reaction.' },
          { level: 20, name: 'Avenging Angel', desc: 'Transform for 10 minutes: fly 60 ft, emanate frightening aura 30 ft (WIS save).' },
        ],
      },
    ],
  },
  {
    id: 'ranger',
    name: 'Ranger',
    hitDie: 'd10',
    primaryAbility: 'Dexterity & Wisdom',
    savingThrows: ['Strength', 'Dexterity'],
    armorProf: 'Light, Medium, Shields',
    weaponProf: 'Simple, Martial',
    color: '#2ECC71',
    emoji: '🏹',
    tagline: 'A warrior who uses nature magic to hunt threats',
    description: 'Far from the bustle of cities and towns, past the hedges that shelter the most distant farms from the terrors of the wild, amid the dense-packed trees of trackless forests, rangers keep their unending watch.',
    keyFeatures: [
      { level: 1, name: 'Spellcasting', desc: 'Half caster using WIS. Prepare spells from the Ranger list.' },
      { level: 1, name: 'Favored Enemy', desc: 'Cast Hunters Mark without a spell slot. Prof bonus uses per long rest. Concentration-free at level 14.' },
      { level: 2, name: 'Fighting Style', desc: 'Choose Archery, Defense, Dueling, or Two-Weapon Fighting.' },
      { level: 2, name: 'Deft Explorer', desc: 'Expertise in one skill, plus additional benefits at levels 6 (extra languages/speed) and 10 (temp HP on short rest).' },
      { level: 5, name: 'Extra Attack', desc: 'Attack twice when you take the Attack action.' },
      { level: 9, name: 'Expertise', desc: 'Double proficiency bonus in two more skills.' },
      { level: 13, name: 'Relentless Hunter', desc: 'Hunters Mark no longer requires concentration.' },
      { level: 14, name: 'Natures Veil', desc: 'As a Bonus Action, become Invisible until start of next turn. Prof bonus uses per long rest.' },
      { level: 18, name: 'Feral Senses', desc: '30 ft of Blindsight.' },
      { level: 20, name: 'Foe Slayer', desc: 'Once per turn, add WIS mod to the attack or damage roll of an attack against a Favored Enemy.' },
    ],
    subclasses: [
      {
        name: 'Beast Master',
        tagline: 'Bond with a Primal Companion',
        description: 'The Beast Master archetype embodies a friendship between the civilized races and the beasts of the wild. You gain a primal beast companion that fights alongside you.',
        features: [
          { level: 3, name: 'Primal Companion', desc: 'Gain a Beast of the Land, Sea, or Sky companion. It acts on your initiative, obeys your commands, and scales with your proficiency bonus.' },
          { level: 7, name: 'Exceptional Training', desc: 'On any turn you dont command your beast, it takes the Dodge action. Your beasts attacks count as magical.' },
          { level: 11, name: 'Bestial Fury', desc: 'Your companion can attack twice when you command it to Attack.' },
          { level: 15, name: 'Share Spells', desc: 'When you cast a spell targeting yourself, it can also affect your companion if its within 30 ft.' },
        ],
      },
      {
        name: 'Fey Wanderer',
        tagline: 'Draw Power from the Feywild',
        description: 'A mysterious and feared frontier ranger, the Fey Wanderer guards the border between the Feywild and the Material Plane. Touched by the feywild, you carry its enchanting presence.',
        features: [
          { level: 3, name: 'Dreadful Strikes', desc: 'Once per turn, add extra Psychic damage (your WIS mod) to a weapon hit.' },
          { level: 3, name: 'Otherworldly Glamour', desc: 'Add WIS mod to CHA checks. Gain proficiency in one CHA skill.' },
          { level: 7, name: 'Beguiling Twist', desc: 'When a creature within 120 ft succeeds on a save against being Charmed or Frightened, redirect the effect to another creature within 120 ft.' },
          { level: 11, name: 'Fey Reinforcements', desc: 'Cast Summon Fey without material components once per long rest. Also always prepared and doesnt count against spells known.' },
          { level: 15, name: 'Misty Wanderer', desc: 'Cast Misty Step without a spell slot (WIS mod times per long rest). Can bring one willing creature within 5 ft.' },
        ],
      },
      {
        name: 'Gloom Stalker',
        tagline: 'Hunt in the Deepest Darkness',
        description: 'Gloom Stalkers are at home in the darkest places, ambushing their foes in shadow. They are often found in the Underdark, but are equally effective in any lightless environment.',
        features: [
          { level: 3, name: 'Dread Ambusher', desc: 'Add WIS mod to initiative. On your first turn in combat, your speed increases by 10 ft and you can make one additional attack (extra 1d8 damage).' },
          { level: 3, name: 'Umbral Sight', desc: '60 ft darkvision (or +60 ft if you already have it). While in darkness, you are invisible to creatures that rely on darkvision to see you.' },
          { level: 7, name: 'Iron Mind', desc: 'Proficiency in WIS saves. If you already have it, gain INT or CHA save proficiency instead.' },
          { level: 11, name: 'Stalkers Flurry', desc: 'Once per turn when you miss an attack, make another attack with the same weapon.' },
          { level: 15, name: 'Shadowy Dodge', desc: 'When a creature attacks you and doesnt have advantage, use Reaction to impose disadvantage.' },
        ],
      },
      {
        name: 'Hunter',
        tagline: 'Hunt the Monsters That Threaten Civilization',
        description: 'The Hunter archetype represents accepting ones place as a bulwark between the civilized lands and the horrors of the wilderness.',
        features: [
          { level: 3, name: 'Hunters Prey', desc: 'Choose Colossus Slayer (extra 1d8 on hit vs injured targets), Horde Breaker (free attack against a second creature within 5 ft of original target), or Giant Killer (Reaction attack when a Large+ creature attacks you).' },
          { level: 7, name: 'Defensive Tactics', desc: 'Choose Escape the Horde (opportunity attacks against you have disadvantage), Multiattack Defense (+4 AC after being hit by a creature), or Steel Will (advantage on saves vs being Frightened).' },
          { level: 11, name: 'Superior Hunters Prey', desc: 'Choose Multiattack: Volley (attack all creatures within 10 ft of a point within range) or Whirlwind Attack (attack all creatures within 5 ft of you).' },
          { level: 15, name: 'Superior Hunters Defense', desc: 'Choose Evasion (no damage on DEX save success, half on fail), Stand Against the Tide (redirect missed attacks to another creature), or Uncanny Dodge (halve damage from an attack you can see).' },
        ],
      },
    ],
  },
  {
    id: 'rogue',
    name: 'Rogue',
    hitDie: 'd8',
    primaryAbility: 'Dexterity',
    savingThrows: ['Dexterity', 'Intelligence'],
    armorProf: 'Light',
    weaponProf: 'Simple, Martial (Finesse)',
    color: '#2C3E50',
    emoji: '🗡️',
    tagline: 'A scoundrel who uses stealth and guile to overcome obstacles',
    description: 'Rogues rely on skill, stealth, and their foes vulnerabilities to get the upper hand. They have a knack for finding the solution to just about any problem, demonstrating a resourcefulness and versatility that is the cornerstone of any successful adventuring party.',
    keyFeatures: [
      { level: 1, name: 'Expertise', desc: 'Double proficiency bonus in two skills. Two more at 6th level.' },
      { level: 1, name: 'Sneak Attack', desc: 'Once per turn, deal extra damage (1d6, scales) with a finesse/ranged weapon when you have advantage or an ally within 5 ft of the target.' },
      { level: 1, name: 'Thieves Cant', desc: 'Secret rogue language — both spoken code and written symbols.' },
      { level: 2, name: 'Cunning Action', desc: 'Bonus Action to Dash, Disengage, or Hide.' },
      { level: 5, name: 'Uncanny Dodge', desc: 'Reaction to halve the damage of an attack you can see.' },
      { level: 7, name: 'Evasion', desc: 'On a DEX save, take no damage on success and half on failure.' },
      { level: 7, name: 'Reliable Talent', desc: 'Any ability check using a proficient skill treats rolls below 10 as a 10.' },
      { level: 14, name: 'Blindsense', desc: 'Aware of the location of any hidden or invisible creature within 10 ft.' },
      { level: 15, name: 'Slippery Mind', desc: 'Proficiency in WIS saves.' },
      { level: 18, name: 'Elusive', desc: 'No attack roll has advantage against you unless you are incapacitated.' },
      { level: 20, name: 'Stroke of Luck', desc: 'Turn a miss into a hit, or turn a failed ability check into a 20. Once per short rest.' },
    ],
    subclasses: [
      {
        name: 'Arcane Trickster',
        tagline: 'Enhance Tricks with Arcane Magic',
        description: 'Arcane Tricksters use enchantment and illusion magic to enhance their natural roguish abilities, creating an invisible mage hand and weaving spells into their attacks.',
        features: [
          { level: 3, name: 'Spellcasting', desc: 'Learn Wizard cantrips and spells (INT-based). Primarily Enchantment and Illusion, with some flexibility. Gain Mage Hand with enhanced capabilities.' },
          { level: 3, name: 'Mage Hand Legerdemain', desc: 'Mage Hand is invisible and can stow/retrieve objects, use thieves tools at range, as a Bonus Action.' },
          { level: 9, name: 'Magical Ambush', desc: 'When you cast a spell while hidden, the target has disadvantage on saves against it.' },
          { level: 13, name: 'Versatile Trickster', desc: 'Use Mage Hand to gain advantage on attacks against a creature within 5 ft of the hand.' },
          { level: 17, name: 'Spell Thief', desc: 'When a creature casts a spell targeting you, make an ability check to steal it. You can cast it for free within 8 hours. The creature cant cast it for 8 hours.' },
        ],
      },
      {
        name: 'Assassin',
        tagline: 'A Master of Deadly Precision',
        description: 'You focus your training on the grim art of death. Those who adhere to this archetype are diverse: hired killers, spies, bounty hunters, and even specially anointed priests trained to exterminate enemies of their deity.',
        features: [
          { level: 3, name: 'Assassinate', desc: 'Advantage on attacks against creatures that havent taken a turn. Hits against surprised creatures are automatic critical hits.' },
          { level: 3, name: 'Assassins Tools', desc: 'Proficiency with disguise kit and poisoners kit.' },
          { level: 9, name: 'Infiltration Expertise', desc: 'Can unfailingly create false identities and forge documents with disguise kit.' },
          { level: 13, name: 'Envenom Weapons', desc: 'As a Bonus Action, apply poison to a weapon. Next hit deals extra Poison damage equal to your Sneak Attack dice (WIS save for half). Three uses per long rest.' },
          { level: 17, name: 'Death Strike', desc: 'When you hit a surprised creature, it must make a CON save or the damage is doubled.' },
        ],
      },
      {
        name: 'Soulknife',
        tagline: 'Strike with Psionic Blades',
        description: 'A Soulknife strikes with the mind, cutting through physical and psychic barriers alike. They are most often found as spies and assassins who use psionic blades of energy.',
        features: [
          { level: 3, name: 'Psionic Power', desc: 'Gain Psionic Energy dice (d6, scales). Use for Psi-Bolstered Knack (add die to failed ability checks) or Psychic Whispers (telepathic communication for hours).' },
          { level: 3, name: 'Psychic Blades', desc: 'Summon blades of psychic energy. Main hand deals 1d6 + ability mod Psychic. Bonus action attack deals 1d4 Psychic. Qualify for Sneak Attack.' },
          { level: 9, name: 'Soul Blades', desc: 'Homing Strikes (add Psionic Energy die to missed attack rolls) and Psychic Teleportation (teleport up to 10x Psionic Energy die result).' },
          { level: 13, name: 'Psychic Veil', desc: 'As a Bonus Action, become Invisible for 1 hour or until you attack/force a save. Once free, then costs Psionic Energy die.' },
          { level: 17, name: 'Rend Mind', desc: 'After dealing Sneak Attack with Psychic Blades, force a WIS save. On failure, target is Stunned for 1 minute.' },
        ],
      },
      {
        name: 'Thief',
        tagline: 'The Classic Treasure-Seeking Rogue',
        description: 'You hone your skills in the larcenous arts. Thieves master climbing, sneaking, and picking locks with supernatural speed and grace.',
        features: [
          { level: 3, name: 'Fast Hands', desc: 'Cunning Action lets you also Use an Object, use Thieves Tools, or Use Magic Device as a Bonus Action.' },
          { level: 3, name: 'Second-Story Work', desc: 'Climbing costs no extra movement. Running jump distance increases by DEX mod feet.' },
          { level: 9, name: 'Supreme Sneak', desc: 'Advantage on Stealth checks if you move no more than half your speed on the same turn.' },
          { level: 13, name: 'Use Magic Device', desc: 'Ignore all class, race, and level requirements on the use of magic items.' },
          { level: 17, name: 'Thiefs Reflexes', desc: 'Take two turns during the first round of combat. First at your normal initiative, second at initiative minus 10.' },
        ],
      },
    ],
  },
  {
    id: 'sorcerer',
    name: 'Sorcerer',
    hitDie: 'd6',
    primaryAbility: 'Charisma',
    savingThrows: ['Constitution', 'Charisma'],
    armorProf: 'None',
    weaponProf: 'Simple',
    color: '#E74C3C',
    emoji: '🔥',
    tagline: 'A spellcaster who draws on inherent magical power',
    description: 'Sorcerers carry a magical birthright conferred upon them by an exotic bloodline, some otherworldly influence, or exposure to unknown cosmic forces. Unlike wizards, sorcerers dont study spellbooks — their power is innate.',
    keyFeatures: [
      { level: 1, name: 'Spellcasting', desc: 'Full caster using CHA. Known spells from the Sorcerer list.' },
      { level: 2, name: 'Font of Magic / Sorcery Points', desc: 'Pool of Sorcery Points equal to Sorcerer level. Convert between spell slots and Sorcery Points.' },
      { level: 2, name: 'Metamagic', desc: 'Modify spells in powerful ways. Choose from options like Twinned Spell, Quickened Spell, Subtle Spell, Heightened Spell, and more.' },
      { level: 5, name: 'Sorcerous Restoration', desc: 'Regain Sorcery Points equal to half Sorcerer level (rounded down) when you finish a long rest at 0 points.' },
      { level: 7, name: 'Sorcery Incarnate', desc: 'While you have Sorcery Points remaining, you can use two Metamagic options on a single spell.' },
      { level: 20, name: 'Arcane Apotheosis', desc: 'While Sorcery Incarnate is active, spending Sorcery Points on Metamagic reduces the cost by 1 (minimum 0).' },
    ],
    subclasses: [
      {
        name: 'Aberrant Sorcery',
        tagline: 'Channel Alien Psionic Power',
        description: 'An alien influence has wrapped its tendrils around your mind, giving you psionic power. You can now touch other minds with that power and alter the world around you by using it.',
        features: [
          { level: 3, name: 'Psionic Spells', desc: 'Additional spells known that dont count against your limit. Includes telepathic and psychic-themed spells.' },
          { level: 3, name: 'Telepathic Speech', desc: 'Communicate telepathically with a creature within 30 ft for a number of minutes equal to Sorcerer level.' },
          { level: 6, name: 'Psionic Sorcery', desc: 'Cast psionic spells by spending Sorcery Points instead of spell slots. When cast this way, requires no verbal or somatic components.' },
          { level: 6, name: 'Psychic Defenses', desc: 'Resistance to Psychic damage. Advantage on saves against Charmed or Frightened.' },
          { level: 14, name: 'Revelation in Flesh', desc: 'Spend Sorcery Points to gain abilities: see invisible, fly, swim/breathe water, or squeeze through 1-inch spaces.' },
          { level: 18, name: 'Warping Implosion', desc: 'Teleport up to 120 ft. Each creature within 30 ft of your departure takes force damage (STR save). On fail, pulled to the space you left.' },
        ],
      },
      {
        name: 'Clockwork Sorcery',
        tagline: 'Channel Cosmic Order',
        description: 'The cosmic force of order has suffused you with magic. That power arises from Mechanus or a similar realm of clockwork order, where every action follows a predetermined pattern.',
        features: [
          { level: 3, name: 'Clockwork Spells', desc: 'Additional spells focused on protection and control. Can swap them for Abjuration or Transmutation spells.' },
          { level: 3, name: 'Restore Balance', desc: 'When a creature within 60 ft makes a roll with advantage or disadvantage, use Reaction to cancel the advantage/disadvantage. Prof bonus uses per long rest.' },
          { level: 6, name: 'Bastion of Law', desc: 'Spend 1-5 Sorcery Points to create a ward on a creature. The ward has d8s equal to the points spent and can absorb damage.' },
          { level: 14, name: 'Trance of Order', desc: 'For 1 minute, attack rolls, ability checks, and saves cant roll below 10. Costs 7 Sorcery Points.' },
          { level: 18, name: 'Clockwork Cavalcade', desc: 'Summon spirits of order in a 30-ft cube. Restore up to 100 HP among creatures, repair damaged objects, and end spells of 6th level or lower.' },
        ],
      },
      {
        name: 'Draconic Sorcery',
        tagline: 'Manifest the Power of Dragons',
        description: 'Your innate magic comes from draconic ancestry. Perhaps your ancestor was a great dragon, or you absorbed the residual magic of a dragons hoard. Either way, dragon blood flows through your veins.',
        features: [
          { level: 3, name: 'Draconic Resilience', desc: 'HP max increases by 3 and by 1 per Sorcerer level. When not wearing armor, AC = 10 + DEX + CHA.' },
          { level: 3, name: 'Draconic Spells', desc: 'Additional spells based on your dragon ancestor type. Command and damage type based on dragon color.' },
          { level: 6, name: 'Elemental Affinity', desc: 'When you cast a damage spell matching your dragon type, add CHA mod to damage. Spend 1 Sorcery Point to gain resistance to that damage type for 1 hour.' },
          { level: 14, name: 'Dragon Wings', desc: 'Sprout dragon wings as a Bonus Action. Fly speed equal to walking speed.' },
          { level: 18, name: 'Dragon Companion', desc: 'You can summon a spectral dragon as a companion.' },
        ],
      },
      {
        name: 'Wild Magic Sorcery',
        tagline: 'Embrace the Chaos of Raw Magic',
        description: 'Your innate magic comes from the wild forces of chaos that underlie the order of creation. A Wild Magic Sorcerer has unpredictable and sometimes dangerous magical surges.',
        features: [
          { level: 3, name: 'Wild Magic Surge', desc: 'After casting a Sorcerer spell, DM can have you roll on the Wild Magic Surge table. Effects are random and range from helpful to chaotic.' },
          { level: 3, name: 'Tides of Chaos', desc: 'Gain advantage on one attack roll, ability check, or save. DM can then trigger a Wild Magic Surge to regain the use.' },
          { level: 6, name: 'Bend Luck', desc: 'Spend 1 Sorcery Point as a Reaction to add or subtract 1d4 from any creatures roll.' },
          { level: 14, name: 'Controlled Chaos', desc: 'When you roll on the Wild Magic Surge table, roll twice and choose which effect occurs.' },
          { level: 18, name: 'Spell Bombardment', desc: 'When you roll damage and get the maximum on a die, roll it again and add the extra result. Once per turn.' },
        ],
      },
    ],
  },
  {
    id: 'warlock',
    name: 'Warlock',
    hitDie: 'd8',
    primaryAbility: 'Charisma',
    savingThrows: ['Wisdom', 'Charisma'],
    armorProf: 'Light',
    weaponProf: 'Simple',
    color: '#9B59B6',
    emoji: '👁️',
    tagline: 'A wielder of magic derived from a pact with an otherworldly being',
    description: 'Warlocks are seekers of the knowledge that lies hidden in the fabric of the multiverse. Through pacts made with mysterious beings of supernatural power, warlocks unlock magical effects both subtle and spectacular.',
    keyFeatures: [
      { level: 1, name: 'Pact Magic', desc: 'Unique spellcasting: few slots (1-4) but they recharge on short rest and are always cast at your highest available level. Uses CHA.' },
      { level: 1, name: 'Eldritch Invocations', desc: 'Gain supernatural abilities. Choose from a wide list that modifies Eldritch Blast, grants at-will spells, or provides unique powers.' },
      { level: 3, name: 'Pact Boon', desc: 'Choose Pact of the Blade (summon magical weapons), Pact of the Chain (enhanced familiar), or Pact of the Tome (extra cantrips and ritual casting).' },
      { level: 9, name: 'Contact Patron', desc: 'Cast Contact Other Plane to reach your patron without expending a spell slot.' },
      { level: 11, name: 'Mystic Arcanum', desc: 'Gain one spell each of 6th, 7th, 8th, and 9th level. Cast each once per long rest without a spell slot.' },
      { level: 20, name: 'Eldritch Master', desc: 'Spend 1 minute entreating your patron to regain all Pact Magic spell slots. Once per long rest.' },
    ],
    subclasses: [
      {
        name: 'Archfey Patron',
        tagline: 'Pact with a Lord of the Feywild',
        description: 'Your patron is a lord or lady of the fey, a creature of legend who holds secrets from before the mortal races were born. Their motivations are often inscrutable, and sometimes whimsical.',
        features: [
          { level: 3, name: 'Steps of the Fey', desc: 'Cast Misty Step without a spell slot. When you do, can either Refresh (gain temp HP) or Taunting (charm a creature near your departure point, WIS save). Prof bonus uses per long rest.' },
          { level: 6, name: 'Misty Escape', desc: 'When you take damage, use Reaction to turn Invisible and teleport up to 60 ft. Invisible until start of next turn.' },
          { level: 10, name: 'Beguiling Defenses', desc: 'Immune to being Charmed. When a creature tries to charm you, use Reaction to turn the charm back on them (WIS save).' },
          { level: 14, name: 'Bewitching Magic', desc: 'When you cast an Enchantment or Illusion spell, can impose Charmed on one target without an additional save.' },
        ],
      },
      {
        name: 'Celestial Patron',
        tagline: 'Pact with a Being of the Upper Planes',
        description: 'Your patron is a powerful being of the Upper Planes. Your pact with that being allows you to experience the barest touch of the holy light that illuminates the multiverse.',
        features: [
          { level: 3, name: 'Healing Light', desc: 'Pool of d6s equal to 1 + Warlock level. As a Bonus Action, heal a creature within 60 ft by spending dice (max prof bonus dice at once).' },
          { level: 6, name: 'Radiant Soul', desc: 'Resistance to Radiant damage. When you deal fire or radiant damage, add CHA mod to one roll.' },
          { level: 10, name: 'Celestial Resilience', desc: 'Gain temp HP equal to Warlock level + CHA mod when you finish a short or long rest. Choose up to 5 allies to gain temp HP equal to half your Warlock level + CHA mod.' },
          { level: 14, name: 'Searing Vengeance', desc: 'When you make a death saving throw, can instead spring to your feet with half HP. Creatures within 30 ft take radiant damage and are blinded. Once per long rest.' },
        ],
      },
      {
        name: 'Fiend Patron',
        tagline: 'Pact with a Lord of the Lower Planes',
        description: 'You have made a pact with a fiend from the lower planes of existence. Fiends powerful enough to forge a pact include demon lords, archdevils, and other dread beings.',
        features: [
          { level: 3, name: 'Dark Ones Blessing', desc: 'When you reduce a hostile creature to 0 HP, gain temp HP equal to CHA mod + Warlock level.' },
          { level: 6, name: 'Dark Ones Own Luck', desc: 'When you make an ability check or save, add 1d10 to the roll. Prof bonus uses per long rest.' },
          { level: 10, name: 'Fiendish Resilience', desc: 'After a short or long rest, choose a damage type (except Force). You have resistance to it until you choose a different one.' },
          { level: 14, name: 'Hurl Through Hell', desc: 'When you hit a creature, send it to the Lower Planes until end of your next turn. When it returns, it takes 10d10 Psychic damage. Once per long rest.' },
        ],
      },
      {
        name: 'Great Old One Patron',
        tagline: 'Pact with an Incomprehensible Entity',
        description: 'Your patron is a mysterious entity whose nature is utterly foreign to the fabric of reality. It might come from the Far Realm or be one of the elder gods known only in legends.',
        features: [
          { level: 3, name: 'Awakened Mind', desc: 'Communicate telepathically with any creature within 30 ft. It doesnt need to share a language. You gain the Detect Thoughts spell as a bonus spell.' },
          { level: 6, name: 'Psychic Spells', desc: 'When you deal damage with a Warlock spell, can change the type to Psychic. Also gain advantage on one Intelligence, Wisdom, or Charisma save per long rest.' },
          { level: 10, name: 'Clairvoyant Combatant', desc: 'When you deal Psychic damage, you learn the targets vulnerabilities, resistances, and immunities.' },
          { level: 14, name: 'Create Thrall', desc: 'Cast Summon Aberration without material components. Can be cast once without a spell slot per long rest.' },
        ],
      },
    ],
  },
  {
    id: 'wizard',
    name: 'Wizard',
    hitDie: 'd6',
    primaryAbility: 'Intelligence',
    savingThrows: ['Intelligence', 'Wisdom'],
    armorProf: 'None',
    weaponProf: 'Simple',
    color: '#3498DB',
    emoji: '🧙',
    tagline: 'A scholarly magic-user who commands arcane knowledge',
    description: 'Wizards are supreme magic-users, defined and united as a class by the spells they cast. Drawing on the subtle weave of magic that permeates the cosmos, wizards cast spells of explosive fire, arcing lightning, subtle deception, and brute-force mind control.',
    keyFeatures: [
      { level: 1, name: 'Spellcasting', desc: 'Full caster using INT. Learn spells in a spellbook. Prepare spells daily. Ritual casting available. Largest spell list in the game.' },
      { level: 1, name: 'Arcane Recovery', desc: 'Once per day during a short rest, recover spell slot levels totaling half your Wizard level (rounded up).' },
      { level: 2, name: 'Scholar', desc: 'Gain Expertise in one skill: Arcana, History, Investigation, Medicine, Nature, or Religion.' },
      { level: 5, name: 'Memorize Spell', desc: 'Once per day, replace one prepared spell with another from your spellbook as a Bonus Action.' },
      { level: 18, name: 'Spell Mastery', desc: 'Choose a 1st-level and 2nd-level spell. Cast them at their lowest level without expending a spell slot.' },
      { level: 20, name: 'Signature Spells', desc: 'Choose two 3rd-level spells. Always have them prepared, and can cast each once per short rest without expending a slot.' },
    ],
    subclasses: [
      {
        name: 'Abjurer',
        tagline: 'Specialize in Protective Magic',
        description: 'The School of Abjuration emphasizes magic that blocks, banishes, or protects. Abjurers are sought when baleful spirits require exorcism or important locations must be guarded against magical spying.',
        features: [
          { level: 3, name: 'Arcane Ward', desc: 'When you cast an Abjuration spell, create a ward with HP equal to twice your Wizard level + INT mod. It absorbs damage directed at you.' },
          { level: 6, name: 'Projected Ward', desc: 'When a creature within 30 ft takes damage, use Reaction to have your Arcane Ward absorb the damage instead.' },
          { level: 10, name: 'Spell Breaker', desc: 'When you cast Dispel Magic or Counterspell, add your proficiency bonus to ability checks made as part of the spell.' },
          { level: 14, name: 'Spell Resistance', desc: 'Advantage on saves against spells. Resistance to spell damage.' },
        ],
      },
      {
        name: 'Diviner',
        tagline: 'See What Others Cannot',
        description: 'The counsel of a diviner is sought by royalty and commoners alike. The School of Divination reveals fragments of the future, echoes of the past, and truths hidden by deception.',
        features: [
          { level: 3, name: 'Portent', desc: 'After a long rest, roll two d20s and record them. Replace any attack roll, save, or ability check made by a creature you can see with one of these rolls.' },
          { level: 6, name: 'Expert Divination', desc: 'When you cast a Divination spell of 2nd level or higher, regain a spell slot of lower level (max 5th).' },
          { level: 10, name: 'The Third Eye', desc: 'Choose one: see invisible creatures, see into the Ethereal Plane, read any language, or gain 30 ft darkvision.' },
          { level: 14, name: 'Greater Portent', desc: 'Roll three d20s for Portent instead of two.' },
        ],
      },
      {
        name: 'Evoker',
        tagline: 'Master of Destructive Energy',
        description: 'Evokers focus on magic that creates powerful elemental effects. They learn to harness the raw stuff of the magical universe and bend it to serve their will as a weapon.',
        features: [
          { level: 3, name: 'Sculpt Spells', desc: 'When you cast an Evocation spell, choose a number of creatures equal to 1 + spell level. They automatically succeed on their save and take no damage.' },
          { level: 6, name: 'Potent Cantrip', desc: 'When a creature succeeds on a save against your cantrip, they still take half damage.' },
          { level: 10, name: 'Empowered Evocation', desc: 'Add your INT mod to the damage of Wizard Evocation spells.' },
          { level: 14, name: 'Overchannel', desc: 'When you cast a Wizard spell of 5th level or lower that deals damage, deal maximum damage. Using it more than once before a long rest deals increasing necrotic damage to you.' },
        ],
      },
      {
        name: 'Illusionist',
        tagline: 'Weave Deceptions Made Real',
        description: 'You focus your studies on magic that dazzles the senses, befuddles the mind, and tricks even the wisest folk. Illusionists are some of the most creative and versatile wizards.',
        features: [
          { level: 3, name: 'Improved Illusions', desc: 'Illusion cantrips last 1 minute, can produce sound and images. Can cast one Illusion spell from a prepared list for free per long rest (level 1-3 only, scales).' },
          { level: 6, name: 'Phantasmal Creatures', desc: 'When you cast an Illusion spell, one creature of your choice automatically fails saves against it. The creature realizes it was tricked after the spell ends.' },
          { level: 10, name: 'Illusory Self', desc: 'When a creature hits you with an attack, use Reaction to create an illusory duplicate that takes the hit instead. The attack automatically misses. Prof bonus uses per long rest.' },
          { level: 14, name: 'Illusory Reality', desc: 'When you cast a Wizard Illusion spell, choose one inanimate, nonmagical object in the illusion to make real for 1 minute.' },
        ],
      },
    ],
  },
];