// D&D 5e (2024) Class Detail Data — Level Tables, Skills, Equipment, Multiclass
// Keyed by class id to merge with CLASS_DATA

// Proficiency bonus by level (universal)
const PROF_BONUS = [0, 2, 2, 2, 2, 3, 3, 3, 3, 4, 4, 4, 4, 5, 5, 5, 5, 6, 6, 6, 6];

export const CLASS_DETAILS = {
  barbarian: {
    skillChoices: 'Choose 2: Animal Handling, Athletics, Intimidation, Nature, Perception, or Survival',
    startingEquipment: 'Choose A or B: (A) Greataxe, 4 Handaxes, Explorer\'s Pack, and 15 GP; or (B) 75 GP',
    multiclass: { requirements: 'STR 13', gains: 'Hit Point Die, proficiency with Martial weapons and Shields' },
    tableColumns: ['Rages', 'Rage Dmg', 'Weapon Mastery'],
    levelTable: [
      { features: 'Rage, Unarmored Defense, Weapon Mastery', cols: ['2', '+2', '2'] },
      { features: 'Danger Sense, Reckless Attack', cols: ['2', '+2', '2'] },
      { features: 'Barbarian Subclass, Primal Knowledge', cols: ['3', '+2', '2'] },
      { features: 'Ability Score Improvement', cols: ['3', '+2', '3'] },
      { features: 'Extra Attack, Fast Movement', cols: ['3', '+2', '3'] },
      { features: 'Subclass feature', cols: ['4', '+2', '3'] },
      { features: 'Feral Instinct, Instinctive Pounce', cols: ['4', '+2', '3'] },
      { features: 'Ability Score Improvement', cols: ['4', '+2', '3'] },
      { features: 'Brutal Strike', cols: ['4', '+3', '3'] },
      { features: 'Subclass feature', cols: ['4', '+3', '4'] },
      { features: 'Relentless Rage', cols: ['4', '+3', '4'] },
      { features: 'Ability Score Improvement', cols: ['5', '+3', '4'] },
      { features: 'Improved Brutal Strike', cols: ['5', '+3', '4'] },
      { features: 'Subclass feature', cols: ['5', '+3', '4'] },
      { features: 'Persistent Rage', cols: ['5', '+3', '4'] },
      { features: 'Ability Score Improvement', cols: ['5', '+4', '4'] },
      { features: 'Improved Brutal Strike', cols: ['6', '+4', '4'] },
      { features: 'Indomitable Might', cols: ['6', '+4', '4'] },
      { features: 'Epic Boon', cols: ['6', '+4', '4'] },
      { features: 'Primal Champion', cols: ['6', '+4', '4'] },
    ],
  },
  bard: {
    skillChoices: 'Choose any 3 skills',
    startingEquipment: 'Choose A or B: (A) Leather Armor, 2 Daggers, Musical Instrument, Entertainer\'s Pack, and 19 GP; or (B) 90 GP',
    multiclass: { requirements: 'CHA 13', gains: 'Hit Point Die, one skill proficiency, one Musical Instrument proficiency' },
    tableColumns: ['Bardic Insp. Die', 'Spells Known', 'Cantrips', '1st', '2nd', '3rd', '4th', '5th'],
    levelTable: [
      { features: 'Bardic Inspiration, Spellcasting', cols: ['d6', '4', '2', '2', '—', '—', '—', '—'] },
      { features: 'Expertise, Jack of All Trades', cols: ['d6', '5', '2', '3', '—', '—', '—', '—'] },
      { features: 'Bard Subclass', cols: ['d6', '6', '2', '4', '2', '—', '—', '—'] },
      { features: 'Ability Score Improvement', cols: ['d6', '7', '3', '4', '3', '—', '—', '—'] },
      { features: 'Font of Inspiration', cols: ['d8', '8', '3', '4', '3', '2', '—', '—'] },
      { features: 'Subclass feature', cols: ['d8', '9', '3', '4', '3', '3', '—', '—'] },
      { features: '—', cols: ['d8', '10', '3', '4', '3', '3', '1', '—'] },
      { features: 'Ability Score Improvement', cols: ['d8', '11', '3', '4', '3', '3', '2', '—'] },
      { features: '—', cols: ['d8', '12', '3', '4', '3', '3', '3', '1'] },
      { features: 'Expertise, Magical Secrets', cols: ['d10', '14', '4', '4', '3', '3', '3', '2'] },
      { features: '—', cols: ['d10', '15', '4', '4', '3', '3', '3', '2'] },
      { features: 'Ability Score Improvement', cols: ['d10', '15', '4', '4', '3', '3', '3', '2'] },
      { features: '—', cols: ['d10', '16', '4', '4', '3', '3', '3', '2'] },
      { features: 'Subclass feature', cols: ['d10', '18', '4', '4', '3', '3', '3', '2'] },
      { features: '—', cols: ['d10', '19', '4', '4', '3', '3', '3', '2'] },
      { features: 'Ability Score Improvement', cols: ['d12', '19', '4', '4', '3', '3', '3', '2'] },
      { features: '—', cols: ['d12', '20', '4', '4', '3', '3', '3', '2'] },
      { features: 'Superior Inspiration', cols: ['d12', '22', '4', '4', '3', '3', '3', '2'] },
      { features: 'Epic Boon', cols: ['d12', '22', '4', '4', '3', '3', '3', '2'] },
      { features: 'Words of Creation', cols: ['d12', '22', '4', '4', '3', '3', '3', '2'] },
    ],
  },
  cleric: {
    skillChoices: 'Choose 2: History, Insight, Medicine, Persuasion, or Religion',
    startingEquipment: 'Choose A or B: (A) Chain Shirt, Shield, Mace, Holy Symbol, Priest\'s Pack, and 7 GP; or (B) 110 GP',
    multiclass: { requirements: 'WIS 13', gains: 'Hit Point Die, Shield proficiency' },
    tableColumns: ['Channel Divinity', 'Cantrips', '1st', '2nd', '3rd', '4th', '5th'],
    levelTable: [
      { features: 'Spellcasting, Divine Order', cols: ['—', '3', '2', '—', '—', '—', '—'] },
      { features: 'Channel Divinity', cols: ['2', '3', '3', '—', '—', '—', '—'] },
      { features: 'Cleric Subclass', cols: ['2', '3', '4', '2', '—', '—', '—'] },
      { features: 'Ability Score Improvement', cols: ['2', '4', '4', '3', '—', '—', '—'] },
      { features: 'Sear Undead', cols: ['2', '4', '4', '3', '2', '—', '—'] },
      { features: 'Subclass feature', cols: ['3', '4', '4', '3', '3', '—', '—'] },
      { features: 'Blessed Strikes', cols: ['3', '4', '4', '3', '3', '1', '—'] },
      { features: 'Ability Score Improvement', cols: ['3', '4', '4', '3', '3', '2', '—'] },
      { features: '—', cols: ['3', '4', '4', '3', '3', '3', '1'] },
      { features: 'Divine Intervention', cols: ['3', '5', '4', '3', '3', '3', '2'] },
      { features: '—', cols: ['3', '5', '4', '3', '3', '3', '2'] },
      { features: 'Ability Score Improvement', cols: ['3', '5', '4', '3', '3', '3', '2'] },
      { features: '—', cols: ['3', '5', '4', '3', '3', '3', '2'] },
      { features: 'Improved Blessed Strikes', cols: ['3', '5', '4', '3', '3', '3', '2'] },
      { features: '—', cols: ['3', '5', '4', '3', '3', '3', '2'] },
      { features: 'Ability Score Improvement', cols: ['3', '5', '4', '3', '3', '3', '2'] },
      { features: 'Subclass feature', cols: ['3', '5', '4', '3', '3', '3', '2'] },
      { features: '—', cols: ['4', '5', '4', '3', '3', '3', '2'] },
      { features: 'Epic Boon', cols: ['4', '5', '4', '3', '3', '3', '2'] },
      { features: 'Greater Divine Intervention', cols: ['4', '5', '4', '3', '3', '3', '2'] },
    ],
  },
  druid: {
    skillChoices: 'Choose 2: Arcana, Animal Handling, Insight, Medicine, Nature, Perception, Religion, or Survival',
    startingEquipment: 'Choose A or B: (A) Leather Armor, Shield, Sickle, Druidic Focus, Explorer\'s Pack, Herbalism Kit, and 9 GP; or (B) 50 GP',
    multiclass: { requirements: 'WIS 13', gains: 'Hit Point Die' },
    tableColumns: ['Wild Shape', 'Cantrips', '1st', '2nd', '3rd', '4th', '5th'],
    levelTable: [
      { features: 'Spellcasting, Druidic, Primal Order', cols: ['—', '2', '2', '—', '—', '—', '—'] },
      { features: 'Wild Shape, Wild Companion', cols: ['2/LR', '2', '3', '—', '—', '—', '—'] },
      { features: 'Druid Subclass', cols: ['2/LR', '2', '4', '2', '—', '—', '—'] },
      { features: 'Ability Score Improvement', cols: ['2/LR', '3', '4', '3', '—', '—', '—'] },
      { features: 'Wild Resurgence', cols: ['2/LR', '3', '4', '3', '2', '—', '—'] },
      { features: 'Subclass feature', cols: ['3/LR', '3', '4', '3', '3', '—', '—'] },
      { features: '—', cols: ['3/LR', '3', '4', '3', '3', '1', '—'] },
      { features: 'Ability Score Improvement', cols: ['3/LR', '3', '4', '3', '3', '2', '—'] },
      { features: '—', cols: ['3/LR', '3', '4', '3', '3', '3', '1'] },
      { features: 'Subclass feature', cols: ['3/LR', '4', '4', '3', '3', '3', '2'] },
      { features: '—', cols: ['3/LR', '4', '4', '3', '3', '3', '2'] },
      { features: 'Ability Score Improvement', cols: ['3/LR', '4', '4', '3', '3', '3', '2'] },
      { features: '—', cols: ['3/LR', '4', '4', '3', '3', '3', '2'] },
      { features: 'Subclass feature', cols: ['3/LR', '4', '4', '3', '3', '3', '2'] },
      { features: 'Improved Wild Shape', cols: ['3/LR', '4', '4', '3', '3', '3', '2'] },
      { features: 'Ability Score Improvement', cols: ['4/LR', '4', '4', '3', '3', '3', '2'] },
      { features: '—', cols: ['4/LR', '4', '4', '3', '3', '3', '2'] },
      { features: 'Beast Spells', cols: ['4/LR', '4', '4', '3', '3', '3', '2'] },
      { features: 'Epic Boon', cols: ['4/LR', '4', '4', '3', '3', '3', '2'] },
      { features: 'Archdruid', cols: ['4/LR', '4', '4', '3', '3', '3', '2'] },
    ],
  },
  fighter: {
    skillChoices: 'Choose 2: Acrobatics, Animal Handling, Athletics, History, Insight, Intimidation, Perception, or Survival',
    startingEquipment: 'Choose A or B: (A) Chain Mail, Greatsword, Flail, 8 Javelins, Dungeoneer\'s Pack, and 4 GP; or (B) 175 GP',
    multiclass: { requirements: 'STR 13 or DEX 13', gains: 'Hit Point Die, proficiency with Martial weapons and Shields' },
    tableColumns: ['Second Wind', 'Weapon Mastery'],
    levelTable: [
      { features: 'Fighting Style, Second Wind, Weapon Mastery', cols: ['2', '3'] },
      { features: 'Action Surge, Tactical Mind', cols: ['2', '3'] },
      { features: 'Fighter Subclass', cols: ['2', '3'] },
      { features: 'Ability Score Improvement', cols: ['3', '4'] },
      { features: 'Extra Attack, Tactical Shift', cols: ['3', '4'] },
      { features: 'Subclass feature', cols: ['3', '4'] },
      { features: '—', cols: ['3', '4'] },
      { features: 'Ability Score Improvement', cols: ['3', '4'] },
      { features: 'Indomitable, Tactical Master', cols: ['3', '4'] },
      { features: 'Subclass feature', cols: ['4', '5'] },
      { features: 'Two Extra Attacks', cols: ['4', '5'] },
      { features: 'Ability Score Improvement', cols: ['4', '5'] },
      { features: 'Studied Attacks', cols: ['4', '5'] },
      { features: 'Subclass feature', cols: ['4', '5'] },
      { features: '—', cols: ['4', '5'] },
      { features: 'Ability Score Improvement', cols: ['4', '5'] },
      { features: 'Action Surge (x2), Indomitable (x2)', cols: ['4', '5'] },
      { features: '—', cols: ['4', '5'] },
      { features: 'Epic Boon', cols: ['4', '5'] },
      { features: 'Three Extra Attacks', cols: ['4', '5'] },
    ],
  },
  monk: {
    skillChoices: 'Choose 2: Acrobatics, Athletics, History, Insight, Religion, or Stealth',
    startingEquipment: 'Choose A or B: (A) Spear, 5 Daggers, Artisan\'s Tools or Musical Instrument, Explorer\'s Pack, and 11 GP; or (B) 50 GP',
    multiclass: { requirements: 'DEX 13 and WIS 13', gains: 'Hit Point Die' },
    tableColumns: ['Martial Arts', 'Focus Points', 'Unarmored Movement'],
    levelTable: [
      { features: 'Martial Arts, Unarmored Defense', cols: ['d6', '—', '—'] },
      { features: 'Monk\'s Focus, Unarmored Movement, Uncanny Metabolism', cols: ['d6', '2', '+10 ft'] },
      { features: 'Monk Subclass, Deflect Attacks', cols: ['d6', '3', '+10 ft'] },
      { features: 'Ability Score Improvement, Slow Fall', cols: ['d6', '4', '+10 ft'] },
      { features: 'Extra Attack, Stunning Strike', cols: ['d8', '5', '+10 ft'] },
      { features: 'Subclass feature, Empowered Strikes', cols: ['d8', '6', '+15 ft'] },
      { features: 'Evasion', cols: ['d8', '7', '+15 ft'] },
      { features: 'Ability Score Improvement', cols: ['d8', '8', '+15 ft'] },
      { features: 'Acrobatic Movement', cols: ['d8', '9', '+15 ft'] },
      { features: 'Heightened Focus, Self-Restoration', cols: ['d8', '10', '+20 ft'] },
      { features: 'Subclass feature', cols: ['d10', '11', '+20 ft'] },
      { features: 'Ability Score Improvement', cols: ['d10', '12', '+20 ft'] },
      { features: 'Deflect Energy', cols: ['d10', '13', '+20 ft'] },
      { features: 'Disciplined Survivor', cols: ['d10', '14', '+25 ft'] },
      { features: '—', cols: ['d10', '15', '+25 ft'] },
      { features: 'Ability Score Improvement', cols: ['d10', '16', '+25 ft'] },
      { features: 'Subclass feature', cols: ['d12', '17', '+25 ft'] },
      { features: 'Superior Defense', cols: ['d12', '18', '+30 ft'] },
      { features: 'Epic Boon', cols: ['d12', '19', '+30 ft'] },
      { features: 'Body and Mind', cols: ['d12', '20', '+30 ft'] },
    ],
  },
  paladin: {
    skillChoices: 'Choose 2: Athletics, Insight, Intimidation, Medicine, Persuasion, or Religion',
    startingEquipment: 'Choose A, B, or C: (A) Chain Mail, Shield, Longsword, 6 Javelins, Holy Symbol, Priest\'s Pack, and 9 GP; (B) 150 GP',
    multiclass: { requirements: 'STR 13 and CHA 13', gains: 'Hit Point Die, proficiency with Martial weapons and Shields' },
    tableColumns: ['Channel Divinity', 'Spell Prep.', '1st', '2nd', '3rd', '4th', '5th'],
    levelTable: [
      { features: 'Lay on Hands, Spellcasting, Weapon Mastery', cols: ['—', '2', '2', '—', '—', '—', '—'] },
      { features: 'Fighting Style, Paladin\'s Smite', cols: ['—', '2', '2', '—', '—', '—', '—'] },
      { features: 'Paladin Subclass, Channel Divinity', cols: ['2', '3', '3', '—', '—', '—', '—'] },
      { features: 'Ability Score Improvement', cols: ['2', '3', '3', '—', '—', '—', '—'] },
      { features: 'Extra Attack, Faithful Steed', cols: ['2', '4', '4', '2', '—', '—', '—'] },
      { features: 'Aura of Protection', cols: ['2', '4', '4', '2', '—', '—', '—'] },
      { features: 'Subclass feature', cols: ['2', '5', '4', '3', '—', '—', '—'] },
      { features: 'Ability Score Improvement', cols: ['2', '5', '4', '3', '—', '—', '—'] },
      { features: 'Abjure Foes', cols: ['2', '6', '4', '3', '2', '—', '—'] },
      { features: 'Aura of Courage', cols: ['3', '6', '4', '3', '2', '—', '—'] },
      { features: 'Radiant Strikes', cols: ['3', '7', '4', '3', '3', '—', '—'] },
      { features: 'Ability Score Improvement', cols: ['3', '7', '4', '3', '3', '—', '—'] },
      { features: '—', cols: ['3', '8', '4', '3', '3', '1', '—'] },
      { features: 'Restoring Touch', cols: ['3', '8', '4', '3', '3', '1', '—'] },
      { features: 'Subclass feature', cols: ['3', '9', '4', '3', '3', '2', '—'] },
      { features: 'Ability Score Improvement', cols: ['3', '9', '4', '3', '3', '2', '—'] },
      { features: '—', cols: ['3', '10', '4', '3', '3', '3', '1'] },
      { features: 'Aura Expansion', cols: ['3', '10', '4', '3', '3', '3', '1'] },
      { features: 'Epic Boon', cols: ['4', '11', '4', '3', '3', '3', '2'] },
      { features: 'Subclass feature', cols: ['4', '11', '4', '3', '3', '3', '2'] },
    ],
  },
  ranger: {
    skillChoices: 'Choose 3: Animal Handling, Athletics, Insight, Investigation, Nature, Perception, Stealth, or Survival',
    startingEquipment: 'Choose A or B: (A) Studded Leather Armor, Scimitar, Shortsword, Longbow, 20 Arrows, Quiver, Druidic Focus, Explorer\'s Pack, and 7 GP; or (B) 150 GP',
    multiclass: { requirements: 'DEX 13 and WIS 13', gains: 'Hit Point Die, one skill proficiency from the Ranger list' },
    tableColumns: ['Spell Prep.', 'Favored Enemy', '1st', '2nd', '3rd', '4th', '5th'],
    levelTable: [
      { features: 'Spellcasting, Favored Enemy, Weapon Mastery', cols: ['2', 'd4', '2', '—', '—', '—', '—'] },
      { features: 'Deft Explorer, Fighting Style', cols: ['2', 'd4', '2', '—', '—', '—', '—'] },
      { features: 'Ranger Subclass', cols: ['3', 'd4', '3', '—', '—', '—', '—'] },
      { features: 'Ability Score Improvement', cols: ['3', 'd4', '3', '—', '—', '—', '—'] },
      { features: 'Extra Attack', cols: ['4', 'd6', '4', '2', '—', '—', '—'] },
      { features: 'Roving', cols: ['4', 'd6', '4', '2', '—', '—', '—'] },
      { features: 'Subclass feature', cols: ['5', 'd6', '4', '3', '—', '—', '—'] },
      { features: 'Ability Score Improvement', cols: ['5', 'd6', '4', '3', '—', '—', '—'] },
      { features: 'Expertise', cols: ['6', 'd8', '4', '3', '2', '—', '—'] },
      { features: 'Tireless', cols: ['6', 'd8', '4', '3', '2', '—', '—'] },
      { features: 'Subclass feature', cols: ['7', 'd8', '4', '3', '3', '—', '—'] },
      { features: 'Ability Score Improvement', cols: ['7', 'd8', '4', '3', '3', '—', '—'] },
      { features: 'Relentless Hunter', cols: ['8', 'd10', '4', '3', '3', '1', '—'] },
      { features: 'Nature\'s Veil', cols: ['8', 'd10', '4', '3', '3', '1', '—'] },
      { features: 'Subclass feature', cols: ['9', 'd10', '4', '3', '3', '2', '—'] },
      { features: 'Ability Score Improvement', cols: ['9', 'd10', '4', '3', '3', '2', '—'] },
      { features: '—', cols: ['10', 'd12', '4', '3', '3', '3', '1'] },
      { features: 'Feral Senses', cols: ['10', 'd12', '4', '3', '3', '3', '1'] },
      { features: 'Epic Boon', cols: ['11', 'd12', '4', '3', '3', '3', '2'] },
      { features: 'Foe Slayer', cols: ['11', 'd12', '4', '3', '3', '3', '2'] },
    ],
  },
  rogue: {
    skillChoices: 'Choose 4: Acrobatics, Athletics, Deception, Insight, Intimidation, Investigation, Perception, Performance, Persuasion, Sleight of Hand, or Stealth',
    startingEquipment: 'Choose A or B: (A) Leather Armor, 2 Daggers, Shortsword, Shortbow, 20 Arrows, Quiver, Thieves\' Tools, Burglar\'s Pack, and 8 GP; or (B) 110 GP',
    multiclass: { requirements: 'DEX 13', gains: 'Hit Point Die, one skill proficiency, Thieves\' Tools proficiency' },
    tableColumns: ['Sneak Attack'],
    levelTable: [
      { features: 'Expertise, Sneak Attack, Thieves\' Cant, Weapon Mastery', cols: ['1d6'] },
      { features: 'Cunning Action', cols: ['1d6'] },
      { features: 'Rogue Subclass, Steady Aim', cols: ['2d6'] },
      { features: 'Ability Score Improvement', cols: ['2d6'] },
      { features: 'Cunning Strike, Uncanny Dodge', cols: ['3d6'] },
      { features: 'Expertise, Subclass feature', cols: ['3d6'] },
      { features: 'Evasion, Reliable Talent', cols: ['4d6'] },
      { features: 'Ability Score Improvement', cols: ['4d6'] },
      { features: 'Subclass feature', cols: ['5d6'] },
      { features: 'Ability Score Improvement', cols: ['5d6'] },
      { features: 'Improved Cunning Strike', cols: ['6d6'] },
      { features: 'Ability Score Improvement', cols: ['6d6'] },
      { features: 'Subtle Strikes', cols: ['7d6'] },
      { features: 'Devious Strikes', cols: ['7d6'] },
      { features: '—', cols: ['8d6'] },
      { features: 'Ability Score Improvement', cols: ['8d6'] },
      { features: 'Subclass feature', cols: ['9d6'] },
      { features: 'Elusive', cols: ['9d6'] },
      { features: 'Epic Boon', cols: ['10d6'] },
      { features: 'Stroke of Luck', cols: ['10d6'] },
    ],
  },
  sorcerer: {
    skillChoices: 'Choose 2: Arcana, Deception, Insight, Intimidation, Persuasion, or Religion',
    startingEquipment: 'Choose A or B: (A) Light Crossbow, 20 Bolts, 2 Daggers, Arcane Focus, Dungeoneer\'s Pack, and 28 GP; or (B) 50 GP',
    multiclass: { requirements: 'CHA 13', gains: 'Hit Point Die' },
    tableColumns: ['Sorcery Points', 'Spells Known', 'Cantrips', '1st', '2nd', '3rd', '4th', '5th'],
    levelTable: [
      { features: 'Spellcasting, Innate Sorcery', cols: ['—', '2', '4', '2', '—', '—', '—', '—'] },
      { features: 'Font of Magic, Metamagic', cols: ['2', '4', '4', '3', '—', '—', '—', '—'] },
      { features: 'Sorcerer Subclass', cols: ['3', '5', '4', '4', '2', '—', '—', '—'] },
      { features: 'Ability Score Improvement', cols: ['4', '6', '4', '4', '3', '—', '—', '—'] },
      { features: 'Sorcerous Restoration', cols: ['5', '7', '4', '4', '3', '2', '—', '—'] },
      { features: 'Subclass feature', cols: ['6', '7', '4', '4', '3', '3', '—', '—'] },
      { features: 'Sorcery Incarnate', cols: ['7', '8', '4', '4', '3', '3', '1', '—'] },
      { features: 'Ability Score Improvement', cols: ['8', '8', '4', '4', '3', '3', '2', '—'] },
      { features: '—', cols: ['9', '9', '4', '4', '3', '3', '3', '1'] },
      { features: 'Metamagic', cols: ['10', '10', '5', '4', '3', '3', '3', '2'] },
      { features: '—', cols: ['11', '10', '5', '4', '3', '3', '3', '2'] },
      { features: 'Ability Score Improvement', cols: ['12', '10', '5', '4', '3', '3', '3', '2'] },
      { features: '—', cols: ['13', '11', '5', '4', '3', '3', '3', '2'] },
      { features: 'Subclass feature', cols: ['14', '11', '5', '4', '3', '3', '3', '2'] },
      { features: '—', cols: ['15', '12', '5', '4', '3', '3', '3', '2'] },
      { features: 'Ability Score Improvement', cols: ['16', '12', '5', '4', '3', '3', '3', '2'] },
      { features: 'Metamagic', cols: ['17', '13', '5', '4', '3', '3', '3', '2'] },
      { features: 'Subclass feature', cols: ['18', '13', '5', '4', '3', '3', '3', '2'] },
      { features: 'Epic Boon', cols: ['19', '14', '5', '4', '3', '3', '3', '2'] },
      { features: 'Arcane Apotheosis', cols: ['20', '14', '5', '4', '3', '3', '3', '2'] },
    ],
  },
  warlock: {
    skillChoices: 'Choose 2: Arcana, Deception, History, Intimidation, Investigation, Nature, or Religion',
    startingEquipment: 'Choose A or B: (A) Leather Armor, Sickle, 2 Daggers, Arcane Focus, Book of Shadows, Scholar\'s Pack, and 15 GP; or (B) 100 GP',
    multiclass: { requirements: 'CHA 13', gains: 'Hit Point Die, one skill proficiency from the Warlock list' },
    tableColumns: ['Invocations', 'Cantrips', 'Spells Known', 'Spell Slots', 'Slot Level'],
    levelTable: [
      { features: 'Pact Magic, Eldritch Invocations', cols: ['1', '2', '2', '1', '1st'] },
      { features: 'Magical Cunning', cols: ['3', '2', '3', '2', '1st'] },
      { features: 'Warlock Subclass', cols: ['3', '2', '4', '2', '2nd'] },
      { features: 'Ability Score Improvement', cols: ['3', '3', '5', '2', '2nd'] },
      { features: '—', cols: ['5', '3', '6', '2', '3rd'] },
      { features: 'Subclass feature', cols: ['5', '3', '7', '2', '3rd'] },
      { features: '—', cols: ['6', '3', '8', '2', '4th'] },
      { features: 'Ability Score Improvement', cols: ['6', '3', '9', '2', '4th'] },
      { features: 'Contact Patron', cols: ['7', '3', '10', '2', '5th'] },
      { features: 'Subclass feature', cols: ['7', '4', '10', '2', '5th'] },
      { features: 'Mystic Arcanum (6th)', cols: ['7', '4', '11', '3', '5th'] },
      { features: 'Ability Score Improvement', cols: ['8', '4', '11', '3', '5th'] },
      { features: 'Mystic Arcanum (7th)', cols: ['8', '4', '12', '3', '5th'] },
      { features: 'Subclass feature', cols: ['8', '4', '12', '3', '5th'] },
      { features: 'Mystic Arcanum (8th)', cols: ['9', '4', '13', '3', '5th'] },
      { features: 'Ability Score Improvement', cols: ['9', '4', '13', '3', '5th'] },
      { features: 'Mystic Arcanum (9th)', cols: ['9', '4', '14', '4', '5th'] },
      { features: '—', cols: ['10', '4', '14', '4', '5th'] },
      { features: 'Epic Boon', cols: ['10', '4', '15', '4', '5th'] },
      { features: 'Eldritch Master', cols: ['10', '4', '15', '4', '5th'] },
    ],
  },
  wizard: {
    skillChoices: 'Choose 2: Arcana, History, Insight, Investigation, Medicine, or Religion',
    startingEquipment: 'Choose A or B: (A) 2 Daggers, Arcane Focus, Robe, Spellbook, Scholar\'s Pack, and 5 GP; or (B) 55 GP',
    multiclass: { requirements: 'INT 13', gains: 'Hit Point Die' },
    tableColumns: ['Cantrips', '1st', '2nd', '3rd', '4th', '5th'],
    levelTable: [
      { features: 'Spellcasting, Ritual Adept, Arcane Recovery', cols: ['3', '2', '—', '—', '—', '—'] },
      { features: 'Scholar', cols: ['3', '3', '—', '—', '—', '—'] },
      { features: 'Wizard Subclass', cols: ['3', '4', '2', '—', '—', '—'] },
      { features: 'Ability Score Improvement', cols: ['4', '4', '3', '—', '—', '—'] },
      { features: 'Memorize Spell', cols: ['4', '4', '3', '2', '—', '—'] },
      { features: 'Subclass feature', cols: ['4', '4', '3', '3', '—', '—'] },
      { features: '—', cols: ['4', '4', '3', '3', '1', '—'] },
      { features: 'Ability Score Improvement', cols: ['4', '4', '3', '3', '2', '—'] },
      { features: '—', cols: ['4', '4', '3', '3', '3', '1'] },
      { features: 'Subclass feature', cols: ['5', '4', '3', '3', '3', '2'] },
      { features: '—', cols: ['5', '4', '3', '3', '3', '2'] },
      { features: 'Ability Score Improvement', cols: ['5', '4', '3', '3', '3', '2'] },
      { features: '—', cols: ['5', '4', '3', '3', '3', '2'] },
      { features: 'Subclass feature', cols: ['5', '4', '3', '3', '3', '2'] },
      { features: '—', cols: ['5', '4', '3', '3', '3', '2'] },
      { features: 'Ability Score Improvement', cols: ['5', '4', '3', '3', '3', '2'] },
      { features: '—', cols: ['5', '4', '3', '3', '3', '2'] },
      { features: 'Spell Mastery', cols: ['5', '4', '3', '3', '3', '2'] },
      { features: 'Epic Boon', cols: ['5', '4', '3', '3', '3', '2'] },
      { features: 'Signature Spells', cols: ['5', '4', '3', '3', '3', '2'] },
    ],
  },
};

export { PROF_BONUS };